#!/bin/bash
set -euo pipefail
MYDIR=$(dirname "$(readlink -f "$0")")

# Setup:
# Server has script in the library.
# Web service is registered. "Process response as plain text" option is set.
# Trivial web server returning unix timestamp with fractional part is running.
killall nc || true
killall netxmsd || true
killall nxagentd || true

mv /usr/local/var/lib/netxms/*.db /tmp
nxdbmgr init

sqlite3 /usr/local/var/lib/netxms/netxms.db < "$MYDIR"/db_patch.sql
nohup "$MYDIR"/trivial-web-server &
nxagentd -d -D7
netxmsd -d -D7
sleep 5 # Wait for netxmsd to initialize

# Test 1: with caching disabled
# Runs web service request twice and succeeds only if results are different
# Should succeed.
nxadm -uadmin -pnetxms -s nx2488script

# Test 2: with caching enabled
# Patch DB to enable caching.
killall netxmsd
sleep 15 # Wait for netxmsd to stop and unlock the database
echo "UPDATE websvc_definitions SET cache_retention_time = 1 WHERE name = 'nx2488webservice';" \
| sqlite3 /usr/local/var/lib/netxms/netxms.db
netxmsd -d -D7
sleep 5 # Wait for netxmsd to initialize

# The script should fail this time.
! nxadm -uadmin -pnetxms -s nx2488script
killall netxmsd
killall nxagentd
killall nc
