/* State after the forced repair run. IDs 101-199. */

/* 101: threshold for non-existing DCI was deleted */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM thresholds WHERE threshold_id=999001)=0 THEN 101 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* 102: baseline node, its interface, DCI and threshold survived */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM nodes WHERE id=990002)=1 AND (SELECT count(*) FROM object_properties WHERE object_id IN (990001,990002,990004))=3 AND (SELECT count(*) FROM interfaces WHERE id=990004)=1 AND (SELECT count(*) FROM items WHERE item_id=990005)=1 AND (SELECT count(*) FROM thresholds WHERE threshold_id=990006)=1 THEN 102 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 2: injected orphan rows are gone (103-1xx), negative fixtures survived */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM acl WHERE object_id=999101)=0 THEN 103 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_custom_attributes WHERE object_id=999102)=0 THEN 104 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_urls WHERE object_id=999103)=0 THEN 105 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM trusted_objects WHERE object_id=999104)=0 AND (SELECT count(*) FROM trusted_objects WHERE trusted_object_id=999105)=0 THEN 106 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM responsible_users WHERE object_id=999106)=0 THEN 107 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_access_snapshot WHERE object_id=999107)=0 THEN 108 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM pollable_objects WHERE id=999108)=0 THEN 109 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM dc_targets WHERE id=999109)=0 THEN 110 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM auto_bind_target WHERE object_id=999110)=0 THEN 111 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM versionable_object WHERE object_id=999111)=0 THEN 112 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM maintenance_journal WHERE object_id=999112)=0 THEN 113 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM active_downtimes WHERE object_id=999113)=0 THEN 114 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM downtime_log WHERE object_id=999114)=0 THEN 115 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM container_members WHERE container_id=999115)=0 THEN 116 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM nsmap WHERE subnet_id=999116)=0 AND (SELECT count(*) FROM nsmap WHERE node_id=999117)=0 THEN 117 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM zone_proxies WHERE object_id=999118)=0 AND (SELECT count(*) FROM zone_proxies WHERE proxy_node=999119)=0 THEN 118 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM icmp_statistics WHERE object_id=999120)=0 THEN 119 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM icmp_target_address_list WHERE node_id=999121)=0 THEN 120 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM software_inventory WHERE node_id=999122)=0 THEN 121 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM hardware_inventory WHERE node_id=999123)=0 THEN 122 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM node_components WHERE node_id=999124)=0 THEN 123 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM ospf_areas WHERE node_id=999125)=0 THEN 124 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM ospf_neighbors WHERE node_id=999126)=0 THEN 125 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM node_snmp_agents WHERE node_id=999127)=0 THEN 126 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM interface_address_list WHERE iface_id=999128)=0 THEN 127 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM interface_vlan_list WHERE iface_id=999129)=0 THEN 128 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM cluster_members WHERE cluster_id=999130)=0 THEN 129 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM cluster_sync_subnets WHERE cluster_id=999131)=0 THEN 130 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM rack_passive_elements WHERE rack_id=999132)=0 THEN 131 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM room_passive_elements WHERE room_id=999133)=0 THEN 132 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM physical_links WHERE left_object_id=999134)=0 AND (SELECT count(*) FROM physical_links WHERE right_object_id=999135)=0 THEN 133 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM network_map_elements WHERE map_id=999136)=0 THEN 134 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM network_map_links WHERE map_id=999137)=0 THEN 135 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM network_map_seed_nodes WHERE map_id=999138)=0 AND (SELECT count(*) FROM network_map_seed_nodes WHERE seed_node_id=999139)=0 THEN 136 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM network_map_deleted_nodes WHERE map_id=999140)=0 THEN 137 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM dashboard_elements WHERE dashboard_id=999141)=0 THEN 138 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM dashboard_template_instances WHERE dashboard_template_id=999142)=0 THEN 139 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM dashboard_associations WHERE object_id=999143)=0 THEN 140 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM business_service_downtime WHERE service_id=999144)=0 THEN 141 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM asset_properties WHERE asset_id=999145)=0 THEN 142 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM vpn_connector_networks WHERE vpn_id=999146)=0 THEN 143 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM resource_tags WHERE resource_id=999147)=0 THEN 144 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM observation_point_hosts WHERE point_id=999148)=0 THEN 145 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM ap_common WHERE owner_id=999149)=0 THEN 146 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM cond_dci_map WHERE condition_id=999150)=0 THEN 147 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM port_stop_list WHERE object_id=999151)=0 THEN 148 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_ai_data WHERE object_id=999152)=0 THEN 149 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM interface_address_list WHERE iface_id=0)=0 AND (SELECT count(*) FROM interface_address_list WHERE iface_id=990004)=1 THEN 150 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM acl WHERE object_id=990002 AND user_id=1)=1 AND (SELECT count(*) FROM object_custom_attributes WHERE object_id=990002 AND attr_name='site')=1 AND (SELECT count(*) FROM nsmap WHERE subnet_id=990007)=0 AND (SELECT count(*) FROM subnets WHERE id=990007)=1 THEN 151 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 3 (152-159) */
/* 152: class table and DCI orphans deleted */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM radios WHERE owner_id=999240)=0 AND (SELECT count(*) FROM cluster_resources WHERE cluster_id=999241)=0 AND (SELECT count(*) FROM dashboard_associations WHERE dashboard_id=999242)=0 AND (SELECT count(*) FROM dc_table_columns WHERE table_id=999243)=0 AND (SELECT count(*) FROM dct_threshold_conditions WHERE threshold_id=999244)=0 AND (SELECT count(*) FROM dct_threshold_instances WHERE threshold_id=999245)=0 AND (SELECT count(*) FROM dci_schedules WHERE item_id=999246)=0 AND (SELECT count(*) FROM dci_access WHERE dci_id=999247)=0 THEN 152 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 153: negative fixtures survived: radio of access point 990003, table column of table DCI 990011 */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM radios WHERE owner_id=990003)=1 AND (SELECT count(*) FROM dc_table_columns WHERE table_id=990011)=1 THEN 153 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 154: all proxy and container references on node 990008 reset, nothing else on the row touched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM nodes WHERE id=990008 AND poller_node_id=0 AND proxy_node=0 AND snmp_proxy=0 AND eip_proxy=0 AND icmp_proxy=0 AND ssh_proxy=0 AND netconf_proxy=0 AND vnc_proxy=0 AND mqtt_proxy=0 AND modbus_proxy=0 AND physical_container_id=0 AND primary_ip='10.99.0.8')=1 THEN 154 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 155: other reset references */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT parent_iface FROM interfaces WHERE id=990004)=0 AND (SELECT drilldown_object_id FROM object_properties WHERE object_id=990001)=0 AND (SELECT source_object FROM conditions WHERE id=990012)=0 AND (SELECT forced_context_object_id FROM dashboards WHERE id=990014)=0 AND (SELECT related_object FROM items WHERE item_id=990010)=0 AND (SELECT related_object FROM dc_tables WHERE item_id=990011)=0 THEN 155 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 156: valid related_object of DCI 990005 untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT related_object FROM items WHERE item_id=990005)=990001 THEN 156 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 157: report-only rows retained with every injected reference value untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT zone_guid FROM nodes WHERE id=990008)=999230 AND (SELECT zone_guid FROM subnets WHERE id=990007)=999231 AND (SELECT count(*) FROM dci_delete_list WHERE node_id=999232 AND dci_id=1 AND type='0')=1 AND (SELECT count(*) FROM business_service_checks WHERE id=999233 AND service_id=990020 AND related_object=999233)=1 AND (SELECT count(*) FROM business_service_checks WHERE id=999234 AND service_id=990020 AND prototype_service_id=999234 AND related_object=990002)=1 AND (SELECT count(*) FROM business_service_checks WHERE id=999235 AND service_id=990020 AND related_dci=999235 AND related_object=990002)=1 AND (SELECT count(*) FROM cond_dci_map WHERE condition_id=990012 AND sequence_number=0 AND dci_id=990005 AND node_id=999236)=1 AND (SELECT count(*) FROM cond_dci_map WHERE condition_id=990012 AND sequence_number=1 AND dci_id=999237 AND node_id=990002)=1 AND (SELECT count(*) FROM cond_dci_map WHERE condition_id=990012)=2 AND (SELECT count(*) FROM scheduled_tasks WHERE id=999238 AND object_id=999238)=1 AND (SELECT count(*) FROM dashboard_template_instances WHERE dashboard_template_id=990001 AND instance_object_id=999239 AND instance_dashboard_id=990014)=1 THEN 157 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 4 (158-159) */
/* 158: rows of the missing rule and chain are gone */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_action_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_timer_cancellation_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_time_frame_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_pstorage_actions WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_cattr_actions WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM alarm_category_map WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM policy_chain_call_list WHERE chain_id=0 AND rule_id=999301)=0 AND (SELECT count(*) FROM event_policy WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_chain_acl WHERE chain_id=999303)=0 AND (SELECT count(*) FROM policy_chain_call_list WHERE target_chain_id=999304)=0 AND (SELECT count(*) FROM alarm_category_map WHERE category_id=999305)=0 THEN 158 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 159: rule 990010 and every one of its valid satellite rows survived, including the chain call and category mapping next to the deleted ones, rule 999301 on chain 990064 kept all satellites while its namesake on chain 0 lost them, and the satellites of rule 1 on deleted chain 999302 are gone */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_action_list WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_timer_cancellation_list WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_time_frame_list WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_pstorage_actions WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM policy_cattr_actions WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM event_policy WHERE chain_id=0 AND rule_id=990010)=1 AND (SELECT count(*) FROM alarm_category_map WHERE chain_id=0 AND rule_id=990010 AND category_id=990063)=1 AND (SELECT count(*) FROM policy_chain_call_list WHERE chain_id=0 AND rule_id=990010 AND target_chain_id=990064)=1 AND (SELECT count(*) FROM policy_chain_acl WHERE chain_id=990064)=1 AND (SELECT count(*) FROM event_policy WHERE chain_id=0 AND rule_id<990000)=55 AND (SELECT count(*) FROM event_policy WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_action_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_timer_cancellation_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_time_frame_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_pstorage_actions WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_cattr_actions WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM alarm_category_map WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_chain_call_list WHERE chain_id=990064 AND rule_id=999301)=1 AND (SELECT count(*) FROM policy_action_list WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_timer_cancellation_list WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_time_frame_list WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_pstorage_actions WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_cattr_actions WHERE chain_id=999302)=0 AND (SELECT count(*) FROM alarm_category_map WHERE chain_id=999302)=0 AND (SELECT count(*) FROM policy_chain_call_list WHERE chain_id=999302)=0 THEN 159 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 5 (160-161) */
/* 160: sensor got a lost_ properties row, and nothing else was created for existing objects */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_properties WHERE object_id=999503 AND name='lost_sensor_999503')=1 AND (SELECT count(*) FROM object_properties WHERE name LIKE 'lost_%')=1 THEN 160 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 161: report-only rows untouched: ghost properties, both duplicate pairs */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM object_properties WHERE object_id=999500 AND name='ghost')=1 AND (SELECT count(*) FROM nodes WHERE id IN (999501,999502))=2 AND (SELECT count(*) FROM object_containers WHERE id=999501 AND object_class=5)=1 AND (SELECT count(*) FROM object_containers WHERE id=999502 AND object_class=32)=1 THEN 161 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 6 (162) */
/* 162: report-only rows untouched: both cycle memberships, both GUID holders, both duplicate subnets */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM container_members WHERE (container_id=999600 AND object_id=999601) OR (container_id=999601 AND object_id=999600))=2 AND (SELECT count(*) FROM object_properties WHERE guid='2d1c3ec1-6b8e-4c31-9c11-000000999610')=2 AND (SELECT count(*) FROM subnets WHERE ip_addr='10.99.6.0' AND ip_netmask=24 AND zone_guid=0)=2 THEN 162 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 7 (163-164) */
/* 163: deleted-owner bindings reset on both tables, report-only bindings untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM items WHERE item_id=999705 AND template_id=0 AND template_item_id=0)=1 AND (SELECT count(*) FROM dc_tables WHERE item_id=999708 AND template_id=0 AND template_item_id=0)=1 AND (SELECT count(*) FROM items WHERE item_id=999701 AND template_id=990002 AND template_item_id=999702)=1 AND (SELECT count(*) FROM items WHERE item_id=999703 AND template_id=990040)=1 AND (SELECT count(*) FROM items WHERE item_id=999704 AND template_id=990041)=1 AND (SELECT count(*) FROM items WHERE item_id=999707 AND template_id=990001)=1 THEN 163 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 164: valid bindings untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM items WHERE item_id=990043 AND template_id=990040 AND template_item_id=990042)=1 AND (SELECT count(*) FROM items WHERE item_id=990045 AND template_id=990041 AND template_item_id=990044)=1 AND (SELECT count(*) FROM items WHERE item_id=990046 AND template_id=990041 AND template_item_id=990044)=1 AND (SELECT count(*) FROM items WHERE item_id=990047 AND template_id=990002 AND template_item_id=990010)=1 AND (SELECT count(*) FROM items WHERE item_id=990048 AND template_id=990002 AND template_item_id=990045)=1 THEN 164 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* 165: overlapping cycle, self-membership and diamond memberships untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM container_members WHERE container_id IN (999630,999631,999632))=4 AND (SELECT count(*) FROM container_members WHERE container_id=999640 AND object_id=999640)=1 AND (SELECT count(*) FROM container_members WHERE container_id IN (999650,999651,999652))=4 THEN 165 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 8 (166-167) */
/* 166: peer and path check groups reset as a whole */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM interfaces WHERE id=990004 AND peer_node_id=0 AND peer_if_id=0 AND peer_proto=0 AND peer_last_updated=0)=1 AND (SELECT count(*) FROM nodes WHERE id=990008 AND path_check_reason=0 AND path_check_node_id=0 AND path_check_iface_id=0)=1 THEN 166 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 167: valid peers and path check untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM interfaces WHERE id=990050 AND peer_node_id=990003 AND peer_if_id=990003 AND peer_proto=1 AND peer_last_updated=1700000000)=1 AND (SELECT count(*) FROM interfaces WHERE id=990051 AND peer_node_id=990008 AND peer_if_id=0 AND peer_proto=2)=1 AND (SELECT count(*) FROM nodes WHERE id=990002 AND path_check_reason=1 AND path_check_node_id=990008 AND path_check_iface_id=0)=1 THEN 167 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 9 (168-169) */
/* 168: every bad code reset to the default of its column, except conditions.deactivation_event whose default event 35 was deleted (report only, value retained) */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM thresholds WHERE threshold_id=990006 AND event_code=17 AND rearm_event_code=18)=1 AND (SELECT count(*) FROM dct_thresholds WHERE id=999903 AND activation_event=69 AND deactivation_event=70)=1 AND (SELECT count(*) FROM conditions WHERE id=990012 AND activation_event=34 AND deactivation_event=999906)=1 AND (SELECT count(*) FROM snmp_trap_cfg WHERE trap_id=999907 AND event_code=500)=1 AND (SELECT count(*) FROM event_policy WHERE chain_id=0 AND rule_id=990010 AND alarm_timeout_event=43)=1 THEN 168 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 169: valid references untouched: all 55 seeded rules keep 43, the cross-chain rule keeps 0 */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM snmp_trap_cfg WHERE trap_id=990053 AND event_code=500)=1 AND (SELECT count(*) FROM dct_thresholds WHERE id=990052 AND activation_event=69 AND deactivation_event=70)=1 AND (SELECT count(*) FROM event_policy WHERE chain_id=0 AND rule_id<990000 AND alarm_timeout_event=43)=55 AND (SELECT count(*) FROM event_policy WHERE chain_id=0 AND rule_id<990000)=55 AND (SELECT count(*) FROM event_policy WHERE chain_id=990064 AND rule_id=999301 AND alarm_timeout_event=0)=1 THEN 169 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 10 (170) */
/* 170: report-only action untouched, negatives untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM actions WHERE action_id=999910 AND channel_name='no-such-channel')=1 AND (SELECT count(*) FROM actions WHERE action_id=990060 AND channel_name='forwarder.example')=1 AND (SELECT count(*) FROM actions WHERE action_id=990061 AND channel_name IN (SELECT name FROM notification_channels))=1 AND (SELECT count(*) FROM actions WHERE action_id IN (990065,990066))=2 THEN 170 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;

/* Task 11 (171-173) */
/* 171: deletable references gone, deleted by full key: the shared ID 999960 is gone only from rules 990079 and 990080 */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_source_list WHERE object_id=999950)=0 AND (SELECT count(*) FROM policy_source_list WHERE object_id=999952)=0 AND (SELECT count(*) FROM policy_source_list WHERE object_id=999956)=0 AND (SELECT count(*) FROM policy_source_list WHERE object_id=999957)=0 AND (SELECT count(*) FROM policy_source_list WHERE object_id=999958)=0 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990079 AND object_id=999960)=0 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=990064 AND rule_id=990080 AND object_id=999960)=0 AND (SELECT count(*) FROM policy_event_list WHERE event_code=999954)=0 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990082 AND event_code=999961)=0 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=990064 AND rule_id=990083 AND event_code=999961)=0 THEN 171 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 172: last-entry references retained */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990071 AND object_id=999951)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990073 AND object_id=999953 AND exclusion='1')=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990077 AND object_id=999959)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990078 AND object_id=999960)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990075 AND event_code=999955)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990081 AND event_code=999961)=1 THEN 172 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 173: valid references of every fixture rule survived */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_source_list WHERE rule_id IN (990070,990072,990076,990079,990080) AND object_id=990002)=5 AND (SELECT count(*) FROM policy_event_list WHERE rule_id IN (990074,990082,990083) AND event_code=17)=3 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990010 AND object_id=990002)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990010 AND event_code=17)=1 THEN 173 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 174: audit follow-up cases: first of two dangling events deleted and the last retained, both dangling events beside a valid one deleted, first of two dangling exclusions deleted and the last retained */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990084 AND event_code=999962)=0 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990084 AND event_code=999963)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990085)=1 AND (SELECT count(*) FROM policy_event_list WHERE chain_id=0 AND rule_id=990085 AND event_code=17)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990086 AND object_id=999966)=0 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990086 AND object_id=999967 AND exclusion='1')=1 THEN 174 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 175: references to built-in objects untouched */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM acl WHERE object_id IN (3,4) AND user_id=1)=2 AND (SELECT count(*) FROM container_members WHERE container_id=3 AND object_id=990041)=1 THEN 175 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
/* 176: built-in EPP sources retained, acl row for 8 deleted */
INSERT INTO nxdbmgr_check_assert (id) SELECT CASE WHEN (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990087 AND object_id=1)=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990088 AND object_id=3 AND exclusion='1')=1 AND (SELECT count(*) FROM policy_source_list WHERE chain_id=0 AND rule_id=990089 AND object_id=4)=1 AND (SELECT count(*) FROM policy_source_list WHERE rule_id IN (990087,990088) AND object_id=990002)=2 AND (SELECT count(*) FROM acl WHERE object_id=8 AND user_id=1)=0 THEN 176 ELSE 0 END FROM nxdbmgr_check_assert WHERE id=0;
