TARGET = libnxsrv.dll
TYPE = dll
COMPONENT = server
SOURCES = agent.cpp apinfo.cpp arp.cpp console.cpp entity_mib.cpp hdlink.cpp \
          hostmib.cpp iflist.cpp isc.cpp main.cpp ndd.cpp nobject.cpp \
          snmpproxy.cpp vlan.cpp
RESOURCES = libnxsrv.rc
GENERATED = messages.h MSG00001.bin

CPPFLAGS = /DLIBNXSRV_EXPORTS
LIBS = libnxdb.lib libnxsl.lib libnxsnmp.lib libnetxms.lib jansson.lib pcre16.lib ws2_32.lib 
	  
include ..\..\..\Makefile.inc.w32

libnxsrv.rc: MSG00001.bin
