TARGET = nxmibc.exe
TYPE = exe
SOURCES = lex.parser.cpp mibparse.cpp nxmibc.cpp parser.tab.cpp
GENERATED = lex.parser.cpp parser.tab.hpp parser.tab.cpp
CPPFLAGS = /D__STDC_VERSION__=199901L
LIBS = libnetxms.lib libnxsnmp.lib
	  
include ..\..\..\Makefile.inc.w32

lex.parser.cpp: parser.l parser.tab.cpp parser.tab.hpp
	$(LEX) -Pmp -B -f -8 -olex.parser.cpp parser.l

parser.tab.hpp: parser.tab.cpp

parser.tab.cpp: parser.y
	$(YACC) -b parser -o parser.tab.cpp -d -p mp -t -v parser.y
