#
# Makefile.w32 - slack notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = slack
SOURCES = $(wildcard *.cpp)
DRV_LIBS = -lnxjansson $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
