#!/bin/sh /etc/rc.common

START=50
STOP=50

SERVICE_PID_FILE="/var/run/nxagentd.pid"

start() {        
    /usr/bin/nxagentd -d
}                 

stop() {          
    if [ -s ${SERVICE_PID_FILE} ]; then
        kill $(cat ${SERVICE_PID_FILE})
        return 0
    else
        echo "NetXMS agent: Already stopped"
        return 1
    fi
}

restart() {
    if [ -s ${SERVICE_PID_FILE} ]; then
        kill $(cat ${SERVICE_PID_FILE})
        sleep 1
        /usr/bin/nxagentd -d
        return 0
    else
        /usr/bin/nxagentd -d        
        return 0
    fi
}
