#
# Makefile.w32 - ntopng (ntopng traffic connector module) for Windows/MinGW
# Part of NetXMS project
#
# Note: this module has no MSVC project; sources are taken from Makefile.am.
# It talks to the ntopng REST API v2 via libcurl.
#

MODULE = ntopng
SOURCES = $(wildcard *.cpp)
MOD_LIBS = -lnxjansson $(CURL_LIBS)

include $(TOPDIR)/src/server/module-common.mk
