#
# Makefile.w32 - smseagle notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = smseagle
SOURCES = $(wildcard *.cpp)
DRV_LIBS = $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
