#
# Makefile.w32 - clickhouse performance data storage driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = clickhouse
SOURCES = clickhouse.cpp sender.cpp
DRV_LIBS = $(CURL_LIBS)

include $(TOPDIR)/src/server/pdsdrv/pdsdrv-common.mk
