#
# Makefile.w32 - wmi subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = wmi
SOURCES = acpi.cpp net.cpp sc.cpp wmi.cpp
SA_LIBS = -lwbemuuid

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
