TARGET = java.nsm
TYPE = nsm
SOURCES = main.cpp SubAgent.cpp
CPPFLAGS = /I "$(JDK_BASE)\include" /I "$(JDK_BASE)\include\win32"
LIBS = libnxagent.lib libnxjava.lib libnetxms.lib
SUBDIRS = java
	  
include ..\..\..\..\Makefile.inc.w32
