#
# Makefile.w32 - net-snmp network device driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = net-snmp
SOURCES = generic.cpp net-snmp.cpp teltonika.cpp

include $(TOPDIR)/src/server/drivers/ndd-common.mk
