#
# Makefile.w32 - textfile notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = textfile
SOURCES = $(wildcard *.cpp)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
