#
# Makefile.w32 - aitools (AI assistant server tools module) for Windows/MinGW
# Part of NetXMS project
#

MODULE = aitools
SOURCES = $(wildcard *.cpp)
MOD_LIBS = -lnxsnmp -lnxdb -lnxjansson

include $(TOPDIR)/src/server/module-common.mk
