#!/bin/bash
set -euo pipefail

MY_DIR=$(dirname "$(readlink -f "$0")" )

if ! [[ -f config.log ]]; then
   ./reconf
   rsync -t "$MY_DIR"/netxms-build-tag.h build/netxms-build-tag.h
   CFLAGS='-ggdb3 -O0' \
      CXXFLAGS='-ggdb3 -O0' \
      STRIP=true \
      ./configure --with-clang --with-server --with-sqlite --with-tests --with-agent --with-client --enable-debug
fi
#make clean
make -j"$(nproc)"
make -j"$(nproc)" install
