#
# Makefile.w32 - siemens network device driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = siemens
SOURCES = ruggedcom.cpp siemens.cpp

include $(TOPDIR)/src/server/drivers/ndd-common.mk
