//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nxcon.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_STATE              101
#define ID_LIST_VIEW                    102
#define ID_CONNECT_TO_SERVER            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_PREVIEW_PANE                105
#define IDR_EVENT_EDITOR                105
#define IDC_TOOLBOX_OBJECT_DETAILS      106
#define IDC_EDIT_SEARCH_STRING          107
#define ID_FIND_OBJECT                  108
#define IDR_MAINFRAME                   128
#define IDR_NXCONTYPE                   129
#define IDI_ALARM                       130
#define IDS_NXC_INIT_FAILED             130
#define IDI_SETUP                       131
#define IDI_USERS                       132
#define IDI_USER_GROUP                  132
#define IDR_CTRLPANEL                   133
#define IDI_RULEMGR                     134
#define IDI_EVENT                       135
#define IDR_EVENTS                      137
#define IDR_MAPFRAME                    138
#define IDS_MAPFRAME                    138
#define IDI_NETMAP                      139
#define IDD_LOGIN                       140
#define IDB_LOGIN                       142
#define IDD_PROGRESS                    143
#define IDR_OBJECTS                     144
#define IDI_INTERFACE                   145
#define IDI_NODE                        146
#define IDI_SUBNET                      147
#define IDI_TREE                        148
#define IDD_OBJECT_PROPERTIES           149
#define IDD_DUMMY                       150
#define IDD_EDIT_EVENT                  151
#define IDM_VIEW_SPECIFIC               152
#define IDR_DEBUG_WINDOW                152
#define IDA_MDI_DEFAULT                 153
#define IDA_OBJECT_BROWSER              154
#define IDI_SORT_UP                     156
#define IDI_SORT_DOWN                   157
#define IDD_OBJECT_NODE_GENERAL         159
#define IDD_OBJECT_CAPS                 160
#define IDD_REQUEST_PROCESSING          162
#define IDD_OBJECT_GENERAL              163
#define IDD_OBJECT_SECURITY             164
#define IDI_USER                        165
#define IDI_EVERYONE                    166
#define IDD_SELECT_USER                 167
#define IDC_EDIT_SERVER                 1000
#define IDC_EDIT_LOGIN                  1001
#define IDC_EDIT_PASSWORD               1002
#define IDC_STATIC_TITLE                1003
#define IDC_STATIC_TEXT                 1004
#define IDC_LIST_VIEW                   1005
#define IDC_TREE_VIEW                   1006
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_ID                     1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_DESCRIPTION            1010
#define IDC_COMBO_SEVERITY              1011
#define IDC_CHECK_LOG                   1012
#define IDC_EDIT_PRIMARY_IP             1015
#define IDC_SELECT_IP                   1016
#define IDC_COMBO_AUTH                  1018
#define IDC_EDIT_SECRET                 1019
#define IDC_EDIT_PORT                   1020
#define IDC_EDIT_OID                    1021
#define IDC_COMBO_SNMP_VERSION          1022
#define IDC_EDIT_COMMUNITY              1023
#define IDC_LIST1                       1024
#define IDC_LIST_CAPS                   1024
#define IDC_LIST_USERS                  1024
#define IDC_INFO_TEXT                   1025
#define IDC_EDIT_CLASS                  1026
#define IDC_CHECK_READ                  1027
#define IDC_CHECK_MODIFY                1028
#define IDC_CHECK_WRITE                 1029
#define IDC_CHECK_CREATE                1029
#define IDC_CHECK_DELETE                1030
#define IDC_CHECK_MOVE                  1031
#define IDC_CHECK_INHERIT_RIGHTS        1032
#define IDC_ADD_USER                    1033
#define IDC_DELETE_USER                 1034
#define ID_VIEW_CONTROLPANEL            32771
#define ID_VIEW_EVENTS                  32774
#define ID_VIEW_MAP                     32776
#define ID_VIEW_OBJECTBROWSER           32779
#define ID_VIEW_REFRESH                 32783
#define ID_CONTROLPANEL_EVENTS          32784
#define ID_CONTROLPANEL_USERS           32785
#define ID_EVENTS_DETAILS               32786
#define ID_EVENTS_GOTOSOURCE            32787
#define ID_VIEW_DEBUG                   32788
#define ID_VIEW_EPP                     32789
#define ID_FILE_EXPORT                  32790
#define ID_FILE_PAGESETUP               32792
#define ID_FILE_SETTINGS                32793
#define ID_OBJECT_VIEW_SHOWPREVIEWPANE  32794
#define ID_OBJECT_VIEW_VIEWASTREE       32795
#define ID_OBJECT_VIEW_VIEWASLIST       32796
#define ID_OBJECT_RENAME                32797
#define ID_OBJECT_DELETE                32798
#define ID_OBJECT_PROPERTIES            32799
#define ID_OBJECT_FIND                  32800
#define ID_OBJECT_VIEW_SELECTION        32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32802
#define _APS_NEXT_CONTROL_VALUE         1035
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
