//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nxcon.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_CONNECT            101
#define ID_LIST_VIEW                    102
#define ID_CONNECT_TO_SERVER            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_PREVIEW_PANE                105
#define IDR_EVENT_EDITOR                105
#define IDC_TOOLBOX_OBJECT_DETAILS      106
#define IDR_USER_EDITOR                 106
#define IDC_EDIT_SEARCH_STRING          107
#define IDR_NETWORK_SUMMARY             107
#define ID_FIND_OBJECT                  108
#define IDR_EDIT_DCI                    108
#define IDR_DC_EDITOR                   108
#define IDR_DCI_DATA_VIEW               109
#define ID_INDICATOR_NUM_ROWS           109
#define ID_INDICATOR_CURR_ROW           110
#define IDR_EPP_EDITOR                  110
#define IDC_STATUS_BAR                  111
#define IDC_GRAPH                       112
#define IDR_DCI_HISTORY_GRAPH           113
#define ID_RULE_LIST                    114
#define ID_HEADER_CTRL                  115
#define ID_SIZEBOX                      118
#define IDR_MAINFRAME                   128
#define IDR_NXCONTYPE                   129
#define IDI_ALARM                       130
#define IDS_NXC_INIT_FAILED             130
#define IDI_SETUP                       131
#define IDI_USERS                       132
#define IDR_CTRLPANEL                   133
#define IDI_RULEMGR                     134
#define IDI_EVENT                       135
#define IDI_USER_GROUP                  136
#define IDR_EVENTS                      137
#define IDR_MAPFRAME                    138
#define IDS_MAPFRAME                    138
#define IDI_NETMAP                      139
#define IDD_LOGIN                       140
#define IDR_ALARMS                      141
#define IDB_LOGIN                       142
#define IDD_PROGRESS                    143
#define IDR_OBJECTS                     144
#define IDI_TREE                        148
#define IDD_OBJECT_PROPERTIES           149
#define IDD_DUMMY                       150
#define IDD_EDIT_EVENT                  151
#define IDM_VIEW_SPECIFIC               152
#define IDR_DEBUG_WINDOW                152
#define IDA_MDI_DEFAULT                 153
#define IDA_OBJECT_BROWSER              154
#define IDI_SORT_UP                     156
#define IDI_SORT_DOWN                   157
#define IDD_OBJECT_NODE_GENERAL         159
#define IDD_OBJECT_CAPS                 160
#define IDD_REQUEST_PROCESSING          162
#define IDD_OBJECT_GENERAL              163
#define IDD_OBJECT_SECURITY             164
#define IDI_USER                        165
#define IDI_EVERYONE                    166
#define IDD_SELECT_USER                 167
#define IDD_NEW_USER                    168
#define IDD_USER_PROPERTIES             169
#define IDD_GROUP_PROPERTIES            170
#define IDM_CONTEXT                     171
#define IDD_SET_PASSWORD                172
#define IDI_PASSWORD                    173
#define IDD_DCI_PROPERTIES              174
#define IDD_DCI_COLLECTION              174
#define IDI_GRAPH                       176
#define IDD_DCI_THRESHOLDS              177
#define IDB_UP_ARROW                    178
#define IDB_DOWN_ARROW                  179
#define IDD_THRESHOLD                   180
#define IDD_MIB_BROWSER                 181
#define IDD_SELECT_OBJECT               185
#define IDA_EPP                         188
#define IDD_EDIT_RULE_COMMENT           189
#define IDD_SELECT_EVENT                190
#define IDI_NETWORK                     192
#define IDI_SEVERITY_WARNING            194
#define IDI_SEVERITY_CRITICAL           195
#define IDI_SEVERITY_MAJOR              196
#define IDI_SEVERITY_MINOR              197
#define IDI_SEVERITY_NORMAL             198
#define IDI_LOG                         199
#define IDB_ANY                         201
#define IDD_OBJECT_PRESENTATION         202
#define IDD_EDIT_RULE_SEVERITY          203
#define IDD_EDIT_RULE_ALARM             204
#define IDB_NONE                        205
#define IDI_UNKNOWN                     207
#define IDI_ACK                         208
#define IDI_CONNECT                     209
#define IDA_ALARM_BROWSER               211
#define IDI_EMAIL                       212
#define IDI_SMS                         213
#define IDI_EXEC                        214
#define IDI_REXEC                       215
#define IDC_EDIT_SERVER                 1000
#define IDC_EDIT_LOGIN                  1001
#define IDC_EDIT_PASSWORD               1002
#define IDC_STATIC_TITLE                1003
#define IDC_STATIC_TEXT                 1004
#define IDC_LIST_VIEW                   1005
#define IDC_TREE_VIEW                   1006
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_ID                     1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_DESCRIPTION            1010
#define IDC_COMBO_SEVERITY              1011
#define IDC_CHECK_LOG                   1012
#define IDC_EDIT_PRIMARY_IP             1015
#define IDC_SELECT_IP                   1016
#define IDC_COMBO_AUTH                  1018
#define IDC_EDIT_SECRET                 1019
#define IDC_EDIT_PORT                   1020
#define IDC_EDIT_OID                    1021
#define IDC_COMBO_SNMP_VERSION          1022
#define IDC_EDIT_COMMUNITY              1023
#define IDC_LIST1                       1024
#define IDC_LIST_CAPS                   1024
#define IDC_LIST_USERS                  1024
#define IDC_LIST_MEMBERS                1024
#define IDC_LIST_THRESHOLDS             1024
#define IDC_LIST_OBJECTS                1024
#define IDC_LIST_EVENTS                 1024
#define IDC_INFO_TEXT                   1025
#define IDC_EDIT_CLASS                  1026
#define IDC_CHECK_READ                  1027
#define IDC_CHECK_MODIFY                1028
#define IDC_CHECK_WRITE                 1029
#define IDC_CHECK_CREATE                1029
#define IDC_CHECK_DELETE                1030
#define IDC_CHECK_MOVE                  1031
#define IDC_CHECK_INHERIT_RIGHTS        1032
#define IDC_ADD_USER                    1033
#define IDC_DELETE_USER                 1034
#define IDC_CHECK_ACCESS                1035
#define IDC_CHECK_PROPERTIES            1037
#define IDC_STATIC_HEADER               1038
#define IDC_CHECK_DISABLED              1042
#define IDC_CHECK_PASSWORD              1043
#define IDC_CHECK_MANAGE_USERS          1044
#define IDC_CHECK_VIEW_CONFIG           1045
#define IDC_CHECK_EDIT_CONFIG           1046
#define IDC_CHECK_DROP_CONN             1047
#define IDC_CHECK_VIEW_EVENTDB          1048
#define IDC_CHECK_EDIT_EVENTDB          1049
#define IDC_BUTTON_ADD                  1053
#define IDC_BUTTON_DELETE               1054
#define IDC_EDIT_PASSWD1                1055
#define IDC_EDIT_PASSWD2                1056
#define IDC_BUTTON_SELECT               1062
#define IDC_EDIT_INTERVAL               1064
#define IDC_EDIT_RETENTION              1065
#define IDC_RADIO_ACTIVE                1066
#define IDC_RADIO_DISABLED              1067
#define IDC_RADIO6                      1068
#define IDC_RADIO_NOT_SUPPORTED         1068
#define IDC_RADIO_MSG                   1068
#define IDC_RADIO_EVENT                 1068
#define IDC_COMBO_DT                    1069
#define IDC_COMBO_ORIGIN                1070
#define IDC_BUTTON_MODIFY               1074
#define IDC_BUTTON_MOVEUP               1076
#define IDC_BUTTON_MOVEDOWN             1077
#define IDC_COMBO_FUNCTION              1078
#define IDC_EDIT_ARG1                   1079
#define IDC_COMBO_OPERATION             1080
#define IDC_EDIT_VALUE                  1081
#define IDC_STATIC_FOR                  1083
#define IDC_STATIC_SAMPLES              1084
#define IDC_STATIC_COMPARE              1085
#define IDC_TREE_MIB                    1086
#define IDC_BUTTON_DETAILS              1088
#define IDC_STATIC_DESCRIPTION          1093
#define IDC_STATIC_OID_TEXT             1094
#define IDC_EDIT_OID_TEXT               1095
#define IDC_EDIT_TYPE                   1098
#define IDC_EDIT_STATUS                 1099
#define IDC_EDIT_ACCESS                 1100
#define IDC_STATIC_STATUS               1101
#define IDC_STATIC_ACCESS               1102
#define IDC_STATIC_TYPE                 1103
#define IDC_EDIT_TEXT                   1104
#define IDC_BITMAP                      1105
#define IDC_RADIO_CLEAR                 1108
#define IDC_RADIO_BLOWFISH              1109
#define IDC_CHECK_DEFAULT_IMAGE         1110
#define IDC_STATIC_ICON                 1111
#define ID_SELECT_IMAGE                 1112
#define IDC_CHECK_NORMAL                1113
#define IDC_CHECK_WARNING               1114
#define IDC_CHECK_MINOR                 1115
#define IDC_CHECK_MAJOR                 1116
#define IDC_CHECK_CRITICAL              1117
#define IDC_BUTTON_ALL                  1118
#define IDC_EDIT_KEY                    1121
#define IDC_EDIT_KEYACK                 1122
#define IDC_RADIO_NORMAL                1127
#define IDC_RADIO_WARNING               1128
#define IDC_RADIO_MINOR                 1129
#define IDC_RADIO_MAJOR                 1130
#define IDC_RADIO_CRITICAL              1131
#define IDC_RADIO_NONE                  1132
#define IDC_CHECK_ALARM                 1133
#define IDC_STATIC_MESSAGE              1134
#define IDC_STATIC_ACK                  1135
#define IDC_STATIC_KEY                  1136
#define IDC_STATIC_KEYACK               1137
#define IDC_STATIC_SEVERITY             1138
#define IDC_CHECK_VIEW_ALARMS           1139
#define IDC_CHECK_ACK_ALARMS            1140
#define IDC_CHECK_MANAGE_EPP            1141
#define IDC_CHECK_MANAGE_ACTIONS        1142
#define ID_VIEW_CONTROLPANEL            32771
#define ID_VIEW_EVENTS                  32774
#define ID_VIEW_MAP                     32776
#define ID_VIEW_OBJECTBROWSER           32779
#define ID_VIEW_REFRESH                 32783
#define ID_CONTROLPANEL_EVENTS          32784
#define ID_CONTROLPANEL_USERS           32785
#define ID_EVENTS_DETAILS               32786
#define ID_EVENTS_GOTOSOURCE            32787
#define ID_VIEW_DEBUG                   32788
#define ID_VIEW_EPP                     32789
#define ID_FILE_EXPORT                  32790
#define ID_FILE_PAGESETUP               32792
#define ID_FILE_SETTINGS                32793
#define ID_OBJECT_VIEW_SHOWPREVIEWPANE  32794
#define ID_OBJECT_VIEW_VIEWASTREE       32795
#define ID_OBJECT_VIEW_VIEWASLIST       32796
#define ID_OBJECT_RENAME                32797
#define ID_OBJECT_DELETE                32798
#define ID_OBJECT_PROPERTIES            32799
#define ID_OBJECT_FIND                  32800
#define ID_OBJECT_VIEW_SELECTION        32801
#define ID_USER_DELETE                  32803
#define ID_USER_SETPASSWORD             32804
#define ID_USER_PROPERTIES              32805
#define ID_USER_CREATE_USER             32806
#define ID_USER_CREATE_GROUP            32807
#define ID_USER_RENAME                  32810
#define ID_OBJECT_DATACOLLECTION        32819
#define ID_VIEW_NETWORKSUMMARY          32821
#define ID_OBJECT_MANAGE                32822
#define ID_OBJECT_UNMANAGE              32823
#define ID_ITEM_NEW                     32826
#define ID_ITEM_DELETE                  32827
#define ID_ITEM_EDIT                    32828
#define ID_ITEM_ACTIVATE                32829
#define ID_ITEM_DISABLE                 32830
#define ID_ITEM_SHOWDATA                32836
#define ID_ITEM_GRAPH                   32837
#define ID_TOOLS_MIBBROWSER             32840
#define ID_CONTROLPANEL_EVENTPOLICY     32841
#define ID_POLICY_ADD                   32842
#define ID_POLICY_DELETE                32843
#define ID_POLICY_NEGATECELL            32844
#define ID_TOOLS_ADDNODE                32845
#define ID_POLICY_INSERTRULE_BELOW      32846
#define ID_POLICY_INSERTRULE_ABOVE      32847
#define ID_POLICY_INSERTRULE_TOP        32848
#define ID_POLICY_INSERTRULE_BOTTOM     32849
#define ID_POLICY_DELETERULE            32850
#define ID_POLICY_DISABLERULE           32851
#define ID_POLICY_ENABLERULE            32852
#define ID_POLICY_EDIT                  32853
#define ID_UPDATE_EVENT_LIST            32855
#define ID_OBJECT_BIND                  32857
#define ID_OBJECT_CREATE_NODE           32860
#define ID_OBJECT_CREATE_CONTAINER      32861
#define ID_VIEW_ALARMS                  32864
#define ID_ALARM_ACKNOWLEGE             32865
#define ID_ALARM_DELETE                 32866
#define ID_ALARM_GOTOSOURCE             32867
#define IDS_GETFOLDERPATH_FAILED        61216
#define IDS_WORKDIR_CREATION_FAILED     61217

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        216
#define _APS_NEXT_COMMAND_VALUE         32871
#define _APS_NEXT_CONTROL_VALUE         1143
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
