//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nxcon.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_CONNECT            101
#define ID_LIST_VIEW                    102
#define ID_INDICATOR_DESKTOP            102
#define ID_CONNECT_TO_SERVER            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_PREVIEW_PANE                105
#define IDC_TOOLBOX_OBJECT_DETAILS      106
#define IDC_EDIT_SEARCH_STRING          107
#define ID_FIND_OBJECT                  108
#define IDR_EDIT_DCI                    108
#define ID_INDICATOR_NUM_ROWS           109
#define ID_INDICATOR_CURR_ROW           110
#define IDR_EPP_EDITOR                  110
#define IDC_STATUS_BAR                  111
#define IDC_GRAPH                       112
#define ID_RULE_LIST                    114
#define ID_HEADER_CTRL                  115
#define ID_SIZEBOX                      118
#define ID_PROGRESS_CTRL                120
#define ID_EDIT_CTRL                    121
#define IDC_SPLITTER                    122
#define ID_WAIT_VIEW                    123
#define ID_BROWSER_CTRL                 124
#define ID_TOOLBAR_CTRL                 126
#define IDR_MAINFRAME                   128
#define ID_TAB_CTRL                     128
#define IDR_NXCONTYPE                   129
#define ID_SEARCH_FIND_FIRST            129
#define IDI_ALARM                       130
#define IDS_NXC_INIT_FAILED             130
#define ID_SEARCH_NEXT_INSTANCE         130
#define IDI_SETUP                       131
#define ID_SEARCH_CLOSE                 131
#define ID_SEARCH_FIND_NEXT             132
#define IDI_RULEMGR                     134
#define ID_TREE_CTRL                    134
#define IDI_EVENT                       135
#define IDI_USER_GROUP                  136
#define IDC_EDIT_LOGIN_NAME             137
#define IDS_MAPFRAME                    138
#define IDI_NETMAP                      139
#define IDD_PROGRESS                    143
#define IDI_TREE                        148
#define IDD_OBJECT_PROPERTIES           149
#define IDD_DUMMY                       150
#define IDD_EDIT_EVENT                  151
#define IDM_VIEW_SPECIFIC               152
#define IDA_MDI_DEFAULT                 153
#define IDA_OBJECT_BROWSER              154
#define IDI_SORT_UP                     156
#define IDA_PACKAGE_MGR                 156
#define IDI_SORT_DOWN                   157
#define IDD_OBJECT_NODE_GENERAL         159
#define IDD_OBJECT_CAPS                 160
#define IDD_REQUEST_PROCESSING          162
#define IDD_OBJECT_GENERAL              163
#define IDD_OBJECT_SECURITY             164
#define IDI_USER                        165
#define IDI_EVERYONE                    166
#define IDD_SELECT_USER                 167
#define IDD_NEW_USER                    168
#define IDD_USER_PROPERTIES             169
#define IDD_GROUP_PROPERTIES            170
#define IDM_CONTEXT                     171
#define IDD_SET_PASSWORD                172
#define IDI_PASSWORD                    173
#define IDD_DCI_PROPERTIES              174
#define IDD_DCI_COLLECTION              174
#define IDI_GRAPH                       176
#define IDD_DCI_THRESHOLDS              177
#define IDB_UP_ARROW                    178
#define IDB_DOWN_ARROW                  179
#define IDD_THRESHOLD                   180
#define IDD_MIB_BROWSER                 181
#define IDD_SELECT_OBJECT               185
#define IDA_EPP                         188
#define IDD_EDIT_RULE_COMMENT           189
#define IDD_SELECT_EVENT                190
#define IDI_NETWORK                     192
#define IDI_SEVERITY_WARNING            194
#define IDI_SEVERITY_CRITICAL           195
#define IDI_SEVERITY_MAJOR              196
#define IDI_SEVERITY_MINOR              197
#define IDI_SEVERITY_NORMAL             198
#define IDI_LOG                         199
#define IDB_ANY                         201
#define IDD_OBJECT_PRESENTATION         202
#define IDD_EDIT_RULE_SEVERITY          203
#define IDD_EDIT_RULE_ALARM             204
#define IDB_NONE                        205
#define IDI_UNKNOWN                     207
#define IDI_ACK                         208
#define IDI_CONNECT                     209
#define IDA_ALARM_BROWSER               211
#define IDI_EMAIL                       212
#define IDI_SMS                         213
#define IDI_EXEC                        214
#define IDI_REXEC                       215
#define IDD_CP_GENERAL                  216
#define IDD_NEW_ACTION                  217
#define IDD_ACTION_PROPERTIES           218
#define IDD_SELECT_ACTION               219
#define IDD_CREATE_CONTAINER            220
#define IDD_CREATE_NODE                 221
#define IDD_DCI_TRANSFORM               222
#define IDI_ACTIVE                      223
#define IDI_DISABLED                    224
#define IDI_UNSUPPORTED                 225
#define IDI_DATACOLLECT                 226
#define IDI_DCT                         227
#define IDD_POLL_NODE                   228
#define IDD_CREATE_TG                   229
#define IDD_CREATE_TEMPLATE             230
#define IDA_NETMAP                      231
#define IDI_OVL_STATUS_MINOR            232
#define IDI_OVL_STATUS_WARNING          233
#define IDI_OVL_STATUS_CRITICAL         234
#define IDI_OVL_STATUS_MAJOR            235
#define IDI_OVL_STATUS_UNKNOWN          236
#define IDI_OVL_STATUS_UNMANAGED        237
#define IDI_OVL_STATUS_DISABLED         238
#define IDI_OVL_STATUS_TESTING          239
#define IDA_EVENT_EDITOR                240
#define IDI_TRAP                        241
#define IDA_ACTION_EDITOR               242
#define IDA_TRAP_EDITOR                 243
#define IDD_DATA_QUERY                  244
#define IDD_EDIT_TRAP                   245
#define IDD_EDIT_TRAP_ARG               246
#define IDA_GRAPH                       247
#define IDD_GRAPH_PROPERTIES            248
#define IDI_PACKAGE                     249
#define IDI_DATABASE                    250
#define IDD_SELECT_INTERNAL_ITEM        252
#define IDD_SELECT_AGENT_PARAM          253
#define IDD_INPUT_BOX                   254
#define IDD_CREATE_NETSRV               255
#define IDD_OBJECT_NETSRV_GENERAL       256
#define IDD_OBJECT_NODE_POLL            257
#define IDI_DEPLOY                      258
#define IDI_NACK                        259
#define IDI_RUNNING                     260
#define IDI_PENDING                     261
#define IDD_OBJECT_RELATIONS            262
#define IDI_TIPS                        264
#define IDD_DESKTOP_SAVE_AS             265
#define IDI_DESKTOP                     266
#define IDA_LAST_VALUES                 268
#define IDD_GRAPH_PROP_SETTINGS         269
#define IDD_GRAPH_PROP_DATA             270
#define IDD_REMOVE_TEMPLATE             271
#define IDD_CHANGE_IP                   272
#define IDD_LASTVAL_PROP                273
#define IDD_DCI_DATA_EXPORT             274
#define IDA_SERVER_CFG_EDITOR           276
#define IDD_EDIT_VARIABLE               277
#define IDD_CREATE_VPNC                 278
#define IDD_OBJECT_VPNC_GENERAL         279
#define IDD_EDIT_IP_SUBNET              280
#define IDA_AGENT_CFG_EDITOR            281
#define IDD_SAVE_AGENT_CFG              282
#define IDI_EDITOR                      283
#define IDA_DC_EDITOR                   284
#define IDI_IEXPLORER                   285
#define IDI_DOCUMENT                    286
#define IDI_LPP                         287
#define IDD_DCI_SCHEDULE                288
#define IDD_OBJECT_STATUS               289
#define IDI_OBJTOOLS                    290
#define IDA_OBJECT_TOOLS_EDITOR         291
#define IDD_OBJTOOL_GENERAL             292
#define IDD_OBJTOOL_COLUMNS             293
#define IDD_NEW_OBJECT_TOOL             294
#define IDI_COMMAND                     295
#define IDD_OBJTOOL_OPTIONS             296
#define IDI_SCRIPT_LIBRARY              297
#define IDI_SCRIPT                      298
#define IDI_CLOSED_FOLDER               299
#define IDI_OPEN_FOLDER                 300
#define IDA_SCRIPT_MANAGER              301
#define IDT_MAP                         302
#define IDD_SNMP_WALK                   304
#define IDI_ZOOMIN                      305
#define IDI_ZOOMOUT                     306
#define IDI_SAVE                        307
#define IDI_PRINT                       308
#define IDI_REFRESH                     309
#define IDI_BACK                        310
#define IDI_FORWARD                     311
#define IDD_SUBMAP_BKGND                312
#define IDI_MODULE                      318
#define IDD_CHANGE_PASSWORD             320
#define IDI_GO_PARENT                   321
#define IDI_HOME                        323
#define IDD_CREATE_CONDITION            324
#define IDD_OBJECT_COND_GENERAL         325
#define IDD_OBJECT_COND_SCRIPT          326
#define IDD_OBJECT_COND_DATA            327
#define IDD_ADD_DCI                     328
#define IDD_COND_DCI_PROP               329
#define IDA_DATA_VIEW                   330
#define IDI_CONFIGS                     331
#define IDA_AGENT_CONFIG_MANAGER        332
#define IDD_AGENT_CONFIG                333
#define IDD_EDIT_RULE_SCRIPT            334
#define IDD_DISCOVERY_GENERAL           336
#define IDD_DISCOVERY_TARGETS           337
#define IDD_DISCOVERY_RANGES            338
#define IDI_DISCOVERY                   339
#define IDD_ADDR_ENTRY                  340
#define IDI_EXIT                        341
#define IDD_CREATE_MP                   342
#define IDI_TEMPLATE_ROOT               343
#define IDD_SELECT_MP                   344
#define IDD_SELECT_TRAP                 345
#define IDD_UPGRADE                     346
#define IDD_CREATE_CLUSTER              347
#define IDD_OBJECT_CLUSTER_GENERAL      348
#define IDD_OBJECT_CLUSTER_RESOURCES    349
#define IDD_CLUSTER_RESOURCE            350
#define IDA_OBJECT_COMMENTS             351
#define IDI_CLUSTER                     352
#define IDI_SERVER                      353
#define IDI_NEXT                        354
#define IDI_FIND                        355
#define IDB_CLOSE                       356
#define IDI_AGAIN                       357
#define IDD_FATAL_ERROR                 358
#define IDD_DEFINE_GRAPH                359
#define IDD_MANAGE_GRAPHS               360
#define IDD_GRAPH_PROP_STYLES           361
#define IDI_CERT                        362
#define IDI_CERTMGR                     363
#define IDD_IMPORT_CA_CERT              364
#define IDA_CERT_MANAGER                365
#define IDI_TOPOLOGY                    366
#define IDI_EMPTY                       367
#define IDD_SET_CHILD_MGMT_STATUS       368
#define IDD_CREATE_IF_DCI               369
#define IDI_SUBORDINATES                371
#define IDI_REDO_LAYOUT                 372
#define IDD_MAP_LINK                    373
#define IDD_OBJECT_IF_GENERAL           374
#define IDD_DISCOVERY_COMMUNITIES       375
#define IDI_STOP                        376
#define IDD_EDIT_RULE_OPTIONS           377
#define IDA_NODE_POLLER                 378
#define IDD_SELECT_SITUATION            379
#define IDI_SITUATION                   380
#define IDA_SITUATION_MANAGER           381
#define IDD_EDIT_RULE_SITUATION         382
#define IDI_INSTANCE                    383
#define IDI_EVENT_CORRELATION           384
#define IDD_OBJECT_TRUSTED_NODES        385
#define IDD_SELECT_MAP                  386
#define IDA_MAP_MANAGER                 387
#define IDD_CREATE_NETMAP               388
#define IDD_OBJECT_CUSTOM_ATTRS         389
#define ID_EDIT_BOX                     525
#define IDC_STATIC_TITLE                1003
#define IDC_STATIC_TEXT                 1004
#define IDC_LIST_VIEW                   1005
#define IDC_TREE_VIEW                   1006
#define IDC_EDIT_NAME                   1007
#define IDC_EDIT_ID                     1008
#define IDC_EDIT_RCPT                   1008
#define IDC_EDIT_MESSAGE                1009
#define IDC_EDIT_SUBJECT                1009
#define IDC_EDIT_DESCRIPTION            1010
#define IDC_COMBO_SEVERITY              1011
#define IDC_CHECK_LOG                   1012
#define IDC_EDIT_PRIMARY_IP             1015
#define IDC_SELECT_IP                   1016
#define IDC_SELECT_POLLER               1017
#define IDC_SELECT_PROXY                1017
#define IDC_COMBO_AUTH                  1018
#define IDC_EDIT_SECRET                 1019
#define IDC_EDIT_PORT                   1020
#define IDC_EDIT_OID                    1021
#define IDC_COMBO_SNMP_VERSION          1022
#define IDC_SELECT_SNMPPROXY            1022
#define IDC_EDIT_COMMUNITY              1023
#define IDC_LIST1                       1024
#define IDC_LIST_CAPS                   1024
#define IDC_LIST_USERS                  1024
#define IDC_LIST_MEMBERS                1024
#define IDC_LIST_THRESHOLDS             1024
#define IDC_LIST_OBJECTS                1024
#define IDC_LIST_EVENTS                 1024
#define IDC_LIST_ARGS                   1024
#define IDC_LIST_PARAMETERS             1024
#define IDC_LIST_PARAMS                 1024
#define IDC_LIST_PARENTS                1024
#define IDC_LIST_DESKTOPS               1024
#define IDC_LIST_LOCAL                  1024
#define IDC_LIST_SCHEDULES              1024
#define IDC_LIST_COLUMNS                1024
#define IDC_LIST_DATA                   1024
#define IDC_LIST_NODES                  1024
#define IDC_LIST_TARGETS                1024
#define IDC_LIST_SUBNETS                1024
#define IDC_LIST_NETWORKS               1024
#define IDC_LIST_RESOURCES              1024
#define IDC_LIST_ITEMS                  1024
#define IDC_LIST_STRINGS                1024
#define IDC_LIST_SITUATIONS             1024
#define IDC_LIST_ATTRIBUTES             1024
#define IDC_LIST_MAPS                   1024
#define IDC_INFO_TEXT                   1025
#define IDC_LIST_CHILDS                 1025
#define IDC_LIST_REMOTE                 1025
#define IDC_EDIT_CLASS                  1026
#define IDC_CHECK_READ                  1027
#define IDC_CHECK_MODIFY                1028
#define IDC_CHECK_WRITE                 1029
#define IDC_CHECK_CREATE                1029
#define IDC_CHECK_DELETE                1030
#define IDC_CHECK_MOVE                  1031
#define IDC_CHECK_INHERIT_RIGHTS        1032
#define IDC_ADD_USER                    1033
#define IDC_DELETE_USER                 1034
#define IDC_CHECK_ACCESS                1035
#define IDC_CHECK_PROPERTIES            1037
#define IDC_STATIC_HEADER               1038
#define IDC_CHECK_DISABLED              1042
#define IDC_CHECK_PASSWORD              1043
#define IDC_CHECK_MANAGE_USERS          1044
#define IDC_CHECK_VIEW_CONFIG           1045
#define IDC_CHECK_EDIT_CONFIG           1046
#define IDC_CHECK_DROP_CONN             1047
#define IDC_CHECK_VIEW_EVENTDB          1048
#define IDC_CHECK_EDIT_EVENTDB          1049
#define IDC_BUTTON_ADD                  1053
#define IDC_BUTTON_DELETE               1054
#define IDC_EDIT_PASSWD1                1055
#define IDC_EDIT_PASSWD2                1056
#define IDC_BUTTON_SELECT               1062
#define IDC_BUTTON_SELECT_REARM_EVENT   1063
#define IDC_BUTTON_SELECT_PROXY         1063
#define IDC_EDIT_INTERVAL               1064
#define IDC_EDIT_RETENTION              1065
#define IDC_RADIO_ACTIVE                1066
#define IDC_RADIO_DISABLED              1067
#define IDC_RADIO6                      1068
#define IDC_RADIO_NOT_SUPPORTED         1068
#define IDC_RADIO_MSG                   1068
#define IDC_RADIO_EVENT                 1068
#define IDC_RADIO_TEXT                  1068
#define IDC_RADIO_MULTIPLE              1068
#define IDC_RADIO_URL                   1068
#define IDC_RADIO_AUTO                  1068
#define IDC_COMBO_DT                    1069
#define IDC_COMBO_ORIGIN                1070
#define IDC_BUTTON_MODIFY               1074
#define IDC_BUTTON_MOVEUP               1076
#define IDC_BUTTON_MOVEDOWN             1077
#define IDC_COMBO_FUNCTION              1078
#define IDC_EDIT_ARG1                   1079
#define IDC_COMBO_OPERATION             1080
#define IDC_EDIT_VALUE                  1081
#define IDC_STATIC_FOR                  1083
#define IDC_STATIC_SAMPLES              1084
#define IDC_STATIC_COMPARE              1085
#define IDC_TREE_MIB                    1086
#define IDC_BUTTON_DETAILS              1088
#define IDC_STATIC_DESCRIPTION          1093
#define IDC_STATIC_OID_TEXT             1094
#define IDC_EDIT_OID_TEXT               1095
#define IDC_EDIT_TYPE                   1098
#define IDC_EDIT_STATUS                 1099
#define IDC_EDIT_ACCESS                 1100
#define IDC_STATIC_STATUS               1101
#define IDC_STATIC_ACCESS               1102
#define IDC_STATIC_TYPE                 1103
#define IDC_EDIT_TEXT                   1104
#define IDC_BITMAP                      1105
#define IDC_RADIO_CLEAR                 1108
#define IDC_RADIO_BLOWFISH              1109
#define IDC_CHECK_DEFAULT_IMAGE         1110
#define IDC_STATIC_ICON                 1111
#define ID_SELECT_IMAGE                 1112
#define IDC_CHECK_NORMAL                1113
#define IDC_CHECK_WARNING               1114
#define IDC_CHECK_MINOR                 1115
#define IDC_CHECK_MAJOR                 1116
#define IDC_CHECK_CRITICAL              1117
#define IDC_BUTTON_ALL                  1118
#define IDC_EDIT_KEY                    1121
#define IDC_EDIT_KEYACK                 1122
#define IDC_EDIT_ACKKEY                 1122
#define IDC_RADIO_NORMAL                1127
#define IDC_RADIO_WARNING               1128
#define IDC_RADIO_MINOR                 1129
#define IDC_RADIO_MAJOR                 1130
#define IDC_RADIO_CRITICAL              1131
#define IDC_RADIO_NONE                  1132
#define IDC_CHECK_ALARM                 1133
#define IDC_STATIC_MESSAGE              1134
#define IDC_STATIC_ACK                  1135
#define IDC_STATIC_KEY                  1136
#define IDC_STATIC_KEYACK               1137
#define IDC_STATIC_ACKKEY               1137
#define IDC_STATIC_SEVERITY             1138
#define IDC_CHECK_VIEW_ALARMS           1139
#define IDC_CHECK_ACK_ALARMS            1140
#define IDC_CHECK_MANAGE_EPP            1141
#define IDC_CHECK_MANAGE_ACTIONS        1142
#define IDC_CHECK_EXPAND                1143
#define IDC_CHECK_MANAGE_PKG            1143
#define IDC_CHECK_GRID                  1144
#define IDC_CHECK_DELETE_ALARMS         1144
#define IDC_RADIO_EXEC                  1147
#define IDC_RADIO_REXEC                 1148
#define IDC_RADIO_EMAIL                 1149
#define IDC_RADIO4                      1150
#define IDC_RADIO_SMS                   1150
#define IDC_RADIO_SEMICOLON             1150
#define IDC_RADIO_MOST_CRITICAL         1150
#define IDC_RADIO_AGENT                 1150
#define IDC_RADIO_SCALE                 1150
#define IDC_LIST_ACTIONS                1152
#define IDC_COMBO_CATEGORY              1154
#define IDC_ICON_PARENT                 1155
#define IDC_STATIC_ID                   1156
#define IDC_STATIC_NAME                 1157
#define IDC_STATIC_CATEGORY             1158
#define IDC_SELECT_PARENT               1159
#define IDC_IP_ADDR                     1161
#define IDC_IP_MASK                     1162
#define IDC_COMBO_DELTA                 1163
#define IDC_EDIT_FORMULA                1164
#define IDC_BUTTON_CREATE               1166
#define IDC_BUTTON_CHECK                1166
#define IDC_BUTTON_TEST                 1166
#define IDC_EDIT_EVENT                  1167
#define IDC_EDIT_REARM_EVENT            1168
#define IDC_POLL_PROGRESS               1169
#define IDC_EDIT_MSG                    1170
#define IDC_CHECK_SAVE                  1172
#define IDC_BUTTON_RESOLVE              1173
#define IDC_BUTTON_NONE                 1174
#define IDC_EDIT_INSTANCE               1175
#define IDC_RADIO_VERSION1              1176
#define IDC_RADIO_VERSION_2C            1177
#define IDC_VERSION                     1178
#define IDC_CHECK_SNMP_TRAPS            1179
#define IDC_CHECK_MANAGE_CONFIG         1180
#define IDC_BUTTON_GET                  1182
#define IDC_BUTTON_RESTART              1185
#define IDC_STATIC_PARAMETER            1186
#define IDC_STATIC_NODE                 1187
#define IDC_EVENT_ICON                  1189
#define IDC_EDIT_TRAP                   1193
#define IDC_SELECT_TRAP                 1194
#define IDC_SELECT_EVENT                1195
#define IDC_BUTTON_UP                   1198
#define IDC_BUTTON_DOWN                 1199
#define IDC_STATIC_INSTANCE             1201
#define IDC_SELECT_OID                  1202
#define IDC_BUTTON_EDIT                 1203
#define IDC_CHECK_AUTOSCALE             1205
#define IDC_CHECK_REFRESH               1206
#define IDC_EDIT_REFRESH                1207
#define IDC_STATIC_REFRESH              1208
#define IDC_STATIC_SECONDS              1209
#define IDC_CB_BACKGROUND               1211
#define IDC_CB_AXIS                     1212
#define IDC_CB_GRID                     1213
#define IDC_STATIC_WARNING_ICON         1213
#define IDC_CB_TEXT                     1214
#define IDC_STATIC_WARNING_TEXT         1214
#define IDC_CB_RULER                    1215
#define IDC_CB_SELECTION                1216
#define IDC_COMBO_TYPES                 1219
#define IDC_RADIO_TCP                   1221
#define IDC_RADIO_UDP                   1222
#define IDC_RADIO_ICMP                  1223
#define IDC_RADIO_OTHER                 1224
#define IDC_EDIT_PROTO                  1225
#define IDC_EDIT_REQUEST                1226
#define IDC_EDIT_RESPONSE               1227
#define IDC_COMBO_TYPE                  1228
#define IDC_EDIT_POLLER                 1232
#define IDC_EDIT_IPADDR                 1233
#define IDC_BUTTON_UNBIND_PARENT        1236
#define IDC_BUTTON_UNBIND_CHILD         1237
#define IDC_RADIO_FIXED                 1240
#define IDC_RADIO_FROM_NOW              1241
#define IDC_DATE_FROM                   1242
#define IDC_TIME_FROM                   1243
#define IDC_DATE_TO                     1244
#define IDC_TIME_TO                     1245
#define IDC_EDIT_COUNT                  1246
#define IDC_COMBO_UNITS                 1247
#define IDC_STATIC_FROM                 1248
#define IDC_STATIC_TO                   1249
#define IDC_RADIO_UNBIND                1254
#define IDC_RADIO_REMOVE                1255
#define IDC_EDIT_TIME                   1258
#define IDC_STATIC_SEC                  1259
#define IDC_STATIC_RCPT                 1261
#define IDC_STATIC_SUBJ                 1262
#define IDC_STATIC_DATA                 1263
#define IDC_STATIC_ENUM                 1264
#define IDC_EDIT_FILE                   1265
#define IDC_STATIC_REGEX                1265
#define IDC_BROWSE                      1266
#define IDC_RADIO_TAB                   1269
#define IDC_RADIO_SPACE                 1270
#define IDC_RADIO_COMMA                 1271
#define IDC_RADIO_RAW                   1272
#define IDC_SELECT_GATEWAY              1275
#define IDC_ADD_LOCAL_NET               1276
#define IDC_REMOVE_LOCAL_NET            1277
#define IDC_ADD_REMOTE_NET              1278
#define IDC_REMOVE_REMOTE_NET           1279
#define IDC_EDIT_GATEWAY                1280
#define IDC_IP_NETMASK                  1283
#define IDC_APPLY                       1284
#define IDC_DISCARD                     1285
#define IDC_SAVE                        1286
#define IDC_CHECK_SCHEDULE              1287
#define IDC_STATIC_INTERVAL             1291
#define IDC_RADIO_UNCHANGED             1292
#define IDC_RADIO_RELATIVE              1294
#define IDC_COMBO_FIXED                 1296
#define IDC_EDIT_RELATIVE               1297
#define IDC_RADIO_SINGLE                1298
#define IDC_EDIT_THRESHOLD              1299
#define IDC_EDIT_T1                     1300
#define IDC_EDIT_T2                     1301
#define IDC_EDIT_T3                     1302
#define IDC_EDIT_T4                     1303
#define IDC_RADIO_SEVERITY              1304
#define IDC_COMBO_S1                    1305
#define IDC_COMBO_S2                    1306
#define IDC_COMBO_S3                    1307
#define IDC_COMBO_S4                    1308
#define IDC_RADIO_CALC_DEFAULT          1310
#define IDC_RADIO_PROP_DEFAULT          1311
#define IDC_EDIT_PROXY                  1311
#define IDC_CHECK_SEND                  1312
#define IDC_EDIT_SNMPPROXY              1312
#define IDC_CHECK_CONTROL               1313
#define IDC_EDIT_DATA                   1316
#define IDC_EDIT_ENUM                   1317
#define IDC_EDIT_REGEX                  1318
#define IDC_RADIO_ACTION                1324
#define IDC_RADIO_COMMAND               1325
#define IDC_RADIO_INTERNAL              1326
#define IDC_RADIO_SNMP                  1327
#define IDC_CHECK_AGENT                 1328
#define IDC_CHECK_SNMP                  1329
#define IDC_CHECK_MATCH_OID             1330
#define IDC_EDIT_TEMPLATE               1331
#define IDC_RADIO_SUFFIX                1332
#define IDC_RADIO_VALUE                 1333
#define IDC_STATIC_SNMP_INDEX           1334
#define IDC_STATIC_SNMP_OPTIONS         1335
#define IDC_STATIC_TEMPLATE             1336
#define IDC_CHECK_RULER                 1337
#define IDC_CHECK_LEGEND                1338
#define IDC_CHECK_DISABLE_AGENT         1339
#define IDC_CHECK_ZOOM                  1339
#define IDC_CHECK_DISABLE_SNMP          1340
#define IDC_CHECK_DISABLE_ICMP          1341
#define IDC_BUTTON_WALK                 1342
#define IDC_RADIO_NBK                   1343
#define IDC_RADIO_BITMAP                1344
#define IDC_RADIO_NO_SCALE              1346
#define IDC_STATIC_FRAME                1348
#define IDC_STATIC_FILE                 1349
#define IDC_STATIC_INFO                 1351
#define IDC_EDIT_ACTIVATION_EVENT       1354
#define IDC_BROWSE_ACTIVATION_EVENT     1355
#define IDC_EDIT_DEACTIVATION_EVENT     1356
#define IDC_BROWSE_DEACTIVATION_EVENT   1357
#define IDC_COMBO_ACTIVE                1358
#define IDC_COMBO_INACTIVE              1359
#define IDC_EDIT_OBJECT                 1360
#define IDC_BROWSE_OBJECT               1361
#define IDC_EDIT_SCRIPT                 1366
#define IDC_LIST_DCI                    1367
#define IDC_LIST2                       1367
#define IDC_LIST_TRAPS                  1367
#define IDC_EDIT_NODE                   1368
#define IDC_EDIT_ITEM                   1369
#define IDC_EDIT_POLLS                  1371
#define IDC_EDIT_FILTER                 1374
#define IDC_EDIT_CONFIG                 1375
#define IDC_BUTTON_GENERATE             1376
#define IDC_CHECK_ENCRYPTION            1377
#define IDC_RADIO_OID                   1378
#define IDC_RADIO_POS                   1379
#define IDC_EDIT_POS                    1380
#define IDC_SPIN_POS                    1382
#define IDC_CHECK_UNMANAGED             1383
#define IDC_CHECK_ICMP                  1386
#define IDC_CHECK_ALL_THRESHOLDS        1388
#define IDC_CHECK_CONFIRM               1389
#define IDC_EDIT_CONFIRM                1390
#define IDC_STATIC_CONFIRM              1391
#define IDC_STATIC_WILLBE               1392
#define IDC_SCRIPT                      1393
#define IDC_RADIO_PASSIVE               1396
#define IDC_RADIO_CUSTOM                1398
#define IDC_CHECK_RANGE                 1403
#define IDC_CHECK_TERM_ALARMS           1409
#define IDC_CHECK_PUSH_DATA             1410
#define IDC_RADIO_SUBNET                1411
#define IDC_RADIO_RANGE                 1412
#define IDC_IPADDR1                     1413
#define IDC_IPADDR2                     1414
#define IDC_STATIC_MASK                 1415
#define IDC_STATIC_ADDR                 1416
#define IDC_TREE_CONTENT                1418
#define IDC_BUTTON_ADD_EVENT            1422
#define IDC_BUTTON_ADD_TEMPLATE         1423
#define IDC_BUTTON_ADD_TRAP             1424
#define IDC_BUTTON_BROWSE               1425
#define IDC_CHECK_REPLACE_BY_CODE       1427
#define IDC_CHECK_REPLACE_BY_NAME       1428
#define IDC_EDIT_URL                    1430
#define IDC_CHECK_HIDE_EMPTY            1431
#define IDC_IPADDR                      1438
#define IDC_COMBO_RESOURCES             1439
#define IDC_TREE_GRAPHS                 1451
#define IDC_BUTTON_PROPERTIES           1452
#define IDC_COMBO_MAPPING               1464
#define IDC_CHECK_MANAGE_TOOLS          1465
#define IDC_CHECK_MANAGE_SCRIPTS        1466
#define IDC_CHECK_VIEW_TRAP_LOG         1467
#define IDC_CHECK_MANAGE_AGENT_CFG      1468
#define IDC_EDIT_MAPPING_DATA           1469
#define IDC_CHECK_MANAGE_MODULES        1470
#define IDC_EDIT_COMMENTS               1472
#define IDC_RADIO_NEWALARM              1475
#define IDC_RADIO_TERMINATE             1476
#define IDC_STATIC_TIMEOUT              1477
#define IDC_EDIT_TIMEOUT                1479
#define IDC_STATIC_EVENT                1480
#define IDC_CHECK_IN                    1481
#define IDC_CHECK_OUT                   1482
#define IDC_CHECK_INP                   1483
#define IDC_CHECK_OUTP                  1484
#define IDC_CHECK_ERRORS_IN             1485
#define IDC_CHECK_ERRORS_OUT            1486
#define IDC_EDIT_IN                     1487
#define IDC_EDIT_OUT                    1488
#define IDC_EDIT_INP                    1489
#define IDC_EDIT_OUTP                   1490
#define IDC_EDIT_IN_ERRORS              1491
#define IDC_EDIT_OUT_ERRORS             1492
#define IDC_CHECK_DELTA_IN              1493
#define IDC_CHECK_DELTA_OUT             1496
#define IDC_EDIT_OBJECT1                1496
#define IDC_CHECK_DELTA_INP             1497
#define IDC_EDIT_PORT1                  1497
#define IDC_CHECK_DELTA_OUTP            1498
#define IDC_SELECT_OBJECT1              1498
#define IDC_CHECK_DELTA_INE             1499
#define IDC_SELECT_PORT1                1499
#define IDC_RADIO_DEFAULT               1499
#define IDC_CHECK_DELTA_OUTE            1500
#define IDC_EDIT_OBJECT2                1500
#define IDC_RADIO_NEVER                 1500
#define IDC_EDIT_PORT2                  1501
#define IDC_RADIO_REPEAT                1501
#define IDC_SELECT_OBJECT2              1502
#define IDC_EDIT_SECONDS                1502
#define IDC_SELECT_PORT2                1503
#define IDC_CHECK_DISABLE_STATUS_POLL   1503
#define IDC_CHECK_DISABLE_CONF_POLLS    1504
#define IDC_CHECK_DISABLE_ROUTE_POLLS   1505
#define IDC_CHECK_DISABLE_DATACOLL      1506
#define IDC_CHECK_USE_MULTIPLIERS       1507
#define IDC_EDIT_TAG                    1508
#define IDC_CHECK_STOP                  1514
#define IDC_CHECK_ENABLE                1516
#define IDC_RADIO_TZLOCAL               1523
#define IDC_RADIO_TZSERVER              1524
#define IDC_RADIO_TZCUSTOM              1525
#define IDC_EDIT_TIMEZONE               1526
#define IDC_CHECK_HOSTNAMES             1527
#define IDC_CHECK_SAVE_GS               1528
#define IDR_WEB_BROWSER                 8100
#define IDR_SYSLOG_BROWSER              8101
#define IDR_LPP_EDITOR                  8102
#define IDR_OBJECT_TOOLS_EDITOR         8103
#define IDR_SCRIPT_MANAGER              8104
#define IDR_EVENT_EDITOR                8105
#define IDR_USER_EDITOR                 8106
#define IDR_NETWORK_SUMMARY             8107
#define IDR_DC_EDITOR                   8108
#define IDR_DCI_DATA_VIEW               8109
#define IDR_TABLE_VIEW                  8110
#define IDR_TRAP_LOG_BROWSER            8111
#define IDR_VIEW_BUILDER                8112
#define IDR_DCI_HISTORY_GRAPH           8113
#define IDR_MODULE_MANAGER              8114
#define IDR_DESKTOP_MANAGER             8115
#define IDR_AGENT_CONFIG_MANAGER        8116
#define IDR_OBJECT_COMMENTS_EDITOR      8117
#define IDR_ALARM_DETAILS               8118
#define IDR_CERT_MANAGER                8119
#define IDR_SITUATION_MANAGER           8120
#define IDR_MAP_MANAGER                 8121
#define IDR_SYSLOG_PARSER_CFG           8122
#define IDR_CTRLPANEL                   8133
#define IDR_EVENTS                      8137
#define IDR_MAPFRAME                    8138
#define IDR_ALARMS                      8141
#define IDR_OBJECTS                     8144
#define IDR_DEBUG_WINDOW                8150
#define IDR_ACTION_EDITOR               8151
#define IDR_NODE_POLLER                 8152
#define IDR_TRAP_EDITOR                 8153
#define IDR_SERVER_CFG_EDITOR           8154
#define IDR_AGENT_CFG_EDITOR            8155
#define IDR_PACKAGE_MGR                 8156
#define IDR_DEPLOYMENT_VIEW             8157
#define IDR_LAST_VALUES_VIEW            8158
#define IDS_INTERNAL_ERROR              20000
#define IDS_WININET_INIT_FAILED         20001
#define IDS_DATA_TRANSFER_ERROR         20002
#define IDS_HTTP_ERROR                  20003
#define IDS_CANNOT_SEND_HTTP_REQUEST    20004
#define IDS_CANNOT_OPEN_HTTP_REQUEST    20005
#define IDS_WININET_CONNECT_FAILED      20006
#define IDS_CAPTION_ERROR               20007
#define IDS_CAPTION_WARNING             20008
#define IDS_CAPTION_INFORMATION         20009
#define IDS_DOWNLOAD_ERROR              20010
#define IDS_BUTTON_NEXT                 20011
#define IDS_BUTTON_FIND                 20012
#define ID_REQUEST_COMPLETED            32125
#define ID_VIEW_CONTROLPANEL            32771
#define ID_VIEW_EVENTS                  32774
#define ID_VIEW_MAP                     32776
#define ID_VIEW_OBJECTBROWSER           32779
#define ID_VIEW_REFRESH                 32783
#define ID_CONTROLPANEL_EVENTS          32784
#define ID_CONTROLPANEL_USERS           32785
#define ID_EVENTS_DETAILS               32786
#define ID_EVENTS_GOTOSOURCE            32787
#define ID_VIEW_DEBUG                   32788
#define ID_VIEW_EPP                     32789
#define ID_FILE_EXPORT                  32790
#define ID_FILE_PAGESETUP               32792
#define ID_FILE_SETTINGS                32793
#define ID_OBJECT_VIEW_SHOWPREVIEWPANE  32794
#define ID_OBJECT_VIEW_VIEWASTREE       32795
#define ID_OBJECT_VIEW_VIEWASLIST       32796
#define ID_OBJECT_RENAME                32797
#define ID_OBJECT_DELETE                32798
#define ID_OBJECT_PROPERTIES            32799
#define ID_OBJECT_FIND                  32800
#define ID_OBJECT_VIEW_SELECTION        32801
#define ID_USER_DELETE                  32803
#define ID_USER_SETPASSWORD             32804
#define ID_USER_PROPERTIES              32805
#define ID_USER_CREATE_USER             32806
#define ID_USER_CREATE_GROUP            32807
#define ID_USER_RENAME                  32810
#define ID_OBJECT_DATACOLLECTION        32819
#define ID_VIEW_NETWORKSUMMARY          32821
#define ID_OBJECT_MANAGE                32822
#define ID_OBJECT_UNMANAGE              32823
#define ID_ITEM_NEW                     32826
#define ID_ITEM_DELETE                  32827
#define ID_ITEM_EDIT                    32828
#define ID_ITEM_ACTIVATE                32829
#define ID_ITEM_DISABLE                 32830
#define ID_ITEM_SHOWDATA                32836
#define ID_ITEM_GRAPH                   32837
#define ID_TOOLS_MIBBROWSER             32840
#define ID_CONTROLPANEL_EVENTPOLICY     32841
#define ID_POLICY_ADD                   32842
#define ID_POLICY_DELETE                32843
#define ID_POLICY_NEGATECELL            32844
#define ID_TOOLS_ADDNODE                32845
#define ID_POLICY_INSERTRULE_BELOW      32846
#define ID_POLICY_INSERTRULE_ABOVE      32847
#define ID_POLICY_INSERTRULE_TOP        32848
#define ID_POLICY_INSERTRULE_BOTTOM     32849
#define ID_POLICY_DELETERULE            32850
#define ID_POLICY_DISABLERULE           32851
#define ID_POLICY_ENABLERULE            32852
#define ID_POLICY_EDIT                  32853
#define ID_UPDATE_EVENT_LIST            32855
#define ID_OBJECT_BIND                  32857
#define ID_OBJECT_CREATE_NODE           32860
#define ID_OBJECT_CREATE_CONTAINER      32861
#define ID_VIEW_ALARMS                  32864
#define ID_ALARM_ACKNOWLEDGE            32865
#define ID_ALARM_DELETE                 32866
#define ID_ALARM_GOTOSOURCE             32867
#define ID_CONTROLPANEL_ACTIONS         32871
#define ID_ACTION_NEW                   32872
#define ID_ACTION_RENAME                32873
#define ID_ACTION_DELETE                32874
#define ID_ACTION_PROPERTIES            32875
#define ID_OBJECT_POLL_STATUS           32876
#define ID_OBJECT_POLL_CONFIGURATION    32877
#define ID_CONTROLPANEL_DCT             32880
#define ID_POLL_RESTART                 32881
#define ID_ITEM_COPY                    32882
#define ID_OBJECT_CREATE_TEMPLATEGROUP  32883
#define ID_OBJECT_CREATE_TEMPLATE       32884
#define ID_OBJECT_OPEN                  32885
#define ID_OBJECT_OPENPARENT            32887
#define ID_ITEM_DUPLICATE               32889
#define ID_OBJECT_WAKEUP                32891
#define ID_EVENT_NEW                    32894
#define ID_EVENT_EDIT                   32895
#define ID_EVENT_DELETE                 32896
#define ID_CONTROLPANEL_SNMPTRAPS       32897
#define ID_POLICY_SAVE                  32898
#define ID_TRAP_NEW                     32899
#define ID_TRAP_EDIT                    32900
#define ID_TRAP_DELETE                  32901
#define ID_TRAP_MOVEUP                  32902
#define ID_TRAP_MOVEDOWN                32903
#define ID_GRAPH_AUTOSCALE              32904
#define ID_GRAPH_PROPERTIES             32905
#define ID_GRAPH_FREEZE                 32906
#define ID_CONTROLPANEL_AGENTPKG        32907
#define ID_PACKAGE_INSTALL              32908
#define ID_PACKAGE_REMOVE               32909
#define ID_PACKAGE_DEPLOY               32910
#define ID_OBJECT_CREATE_SERVICE        32913
#define ID_OBJECT_LASTDCIVALUES         32915
#define ID_OBJECT_APPLY                 32916
#define ID_DESKTOP_SAVE                 32917
#define ID_DESKTOP_SAVEAS               32918
#define ID_DESKTOP_RESTORE              32919
#define ID_GRAPH_PRESETS_LASTHOUR       32920
#define ID_GRAPH_PRESETS_LAST2HOURS     32921
#define ID_GRAPH_PRESETS_LAST4HOURS     32922
#define ID_GRAPH_PRESETS_LASTDAY        32923
#define ID_GRAPH_PRESETS_LASTWEEK       32924
#define ID_GRAPH_PRESETS_LAST10MINUTES  32925
#define ID_GRAPH_PRESETS_LAST30MINUTES  32926
#define ID_OBJECT_UNBIND                32929
#define ID_OBJECT_CHANGEIPADDRESS       32930
#define ID_LASTVALUES_PROPERTIES        32931
#define ID_DESKTOP_NEW                  32933
#define ID_OBJECT_AGENTCFG              32934
#define ID_ITEM_EXPORTDATA              32937
#define ID_CONTROLPANEL_SERVERCFG       32940
#define ID_VARIABLE_EDIT                32941
#define ID_VARIABLE_NEW                 32942
#define ID_VARIABLE_DELETE              32943
#define ID_OBJECT_CREATE_VPNCONNECTOR   32944
#define ID_EDIT_DELETE                  32949
#define ID_CONFIG_SAVE                  32951
#define ID_CONFIG_SAVEANDAPPLY          32952
#define ID_ALARM_SHOWNODES              32953
#define ID_ITEM_MOVETOTEMPLATE          32954
#define ID_VIEW_SYSLOG                  32956
#define ID_CONTROLPANEL_LOGPROCESSING   32957
#define ID_OBJECT_MOVE                  32958
#define ID_CONTROLPANEL_OBJECTTOOLS     32959
#define ID_OBJECTTOOLS_NEW              32960
#define ID_OBJECTTOOLS_EDIT             32961
#define ID_OBJECTTOOLS_DELETE           32962
#define ID_ALARM_ENABLE_SPEAKER         32966
#define ID_ALARM_SOUNDCONFIGURATION     32967
#define ID_CONTROLPANEL_SCRIPTLIBRARY   32968
#define ID_SCRIPT_NEW                   32969
#define ID_SCRIPT_EDIT                  32970
#define ID_SCRIPT_SAVE                  32971
#define ID_SCRIPT_VIEWASLIST            32974
#define ID_SCRIPT_VIEWASTREE            32975
#define ID_SCRIPT_RENAME                32976
#define ID_SCRIPT_DELETE                32977
#define ID_GRAPH_RULER                  32978
#define ID_GRAPH_LEGEND                 32980
#define ID_GRAPH_PRESETS_LASTMONTH      32982
#define ID_GRAPH_PRESETS_LASTYEAR       32983
#define ID_VIEW_SNMPTRAPLOG             32986
#define ID_CONTROLPANEL_VIEWBUILDER     32987
#define ID_BUTTON32988                  32988
#define ID_BUTTON32989                  32989
#define ID_BUTTON32990                  32990
#define ID_BUTTON32992                  32992
#define ID_TOOLS_SNMPWALK               32995
#define ID_MAP_ZOOMIN                   32996
#define ID_MAP_ZOOMOUT                  32997
#define ID_MAP_SAVE                     32998
#define ID_MAP_SHOW_TOOLBOX             33001
#define ID_MAP_SHOW_TOOLBAR             33002
#define ID_MAP_SHOW_STATUSBAR           33003
#define ID_MAP_BACK                     33004
#define ID_MAP_FORWARD                  33005
#define ID_MAP_HOME                     33006
#define ID_MAP_REDOLAYOUT               33007
#define ID_MAP_SETBACKGROUND            33008
#define ID_MAP_PARENT                   33009
#define ID_CONTROLPANEL_MODULES         33010
#define ID_DESKTOP_MANAGE               33012
#define ID_DESKTOP_COPY                 33013
#define ID_DESKTOP_DELETE               33014
#define ID_DESKTOP_MOVE                 33015
#define ID_TOOLS_CHANGEPASSWORD         33016
#define ID_OBJECT_CREATE_CONDITION      33017
#define ID_ITEM_MOVE                    33019
#define ID_DATA_SCALEVALUE              33020
#define ID_DATA_COPYTOCLIPBOARD         33021
#define ID_DATA_SCALE_KBYTES            33022
#define ID_DATA_SCALE_KILO              33023
#define ID_DATA_SCALE_MBYTES            33024
#define ID_DATA_SCALE_MEGA              33025
#define ID_DATA_SCALE_GBYTES            33026
#define ID_DATA_SCALE_GIGA              33027
#define ID_DATA_SCALE_NORMAL            33028
#define ID_CONTROLPANEL_AGENTCONFIGS    33029
#define ID_CONFIG_NEW                   33030
#define ID_CONFIG_EDIT                  33031
#define ID_CONFIG_DELETE                33032
#define ID_CONFIG_MOVEUP                33033
#define ID_CONFIG_MOVEDOWN              33034
#define ID_GRAPH_ZOOMOUT                33037
#define ID_ALARM_TERMINATE              33039
#define ID_ALARM_LASTDCIVALUES          33040
#define ID_OBJECT_COMMENTS              33042
#define ID_COMMENTS_SAVE                33043
#define ID_ALARM_DETAILS                33044
#define ID_CONTROLPANEL_NETWORKDISCOVERY 33046
#define ID_TOOLS_CREATEMP               33047
#define ID_TOOLS_IMPORTMP               33048
#define ID_GRAPH_COPYTOCLIPBOARD        33049
#define ID_OBJECT_CREATE_CLUSTER        33050
#define ID_TOOLS_GRAPHS_MANAGE          33051
#define ID_GRAPH_DEFINE                 33052
#define ID_GRAPHMANAGER_RENAME          33053
#define ID_GRAPHMANAGER_DELETE          33054
#define ID_GRAPHMANAGER_EDIT            33055
#define ID_CONTROLPANEL_CERTIFICATES    33056
#define ID_CERTIFICATE_IMPORT           33057
#define ID_CERTIFICATE_DELETE           33058
#define ID_CERTIFICATE_EDITCOMMENTS     33060
#define ID_STATUS_HIDENORMAL            33062
#define ID_STATUS_HIDEUNMANAGED         33063
#define ID_STATUS_HIDEUNKNOWN           33064
#define ID_STATUS_HIDENONOPERATIONAL    33065
#define ID_STATUS_ICONS                 33066
#define ID_OBJECT_VIEW_CONTAINERSFIRST  33067
#define ID_OBJECT_VIEW_HIDEUNMANAGED    33068
#define ID_OBJECT_SETCHILDMGMT          33069
#define ID_OBJECT_VIEW_FOLLOWOBJECTUPDATES 33070
#define ID_OBJECT_CREATE_IF_DCI         33071
#define ID_SUBORDINATE_MANAGE           33072
#define ID_SUBORDINATE_UNMANAGE         33073
#define ID_SUBORDINATE_UNBIND           33074
#define ID_SUBORDINATE_DELETE           33075
#define ID_SUBORDINATE_PROPERTIES       33076
#define ID_MAP_LINK                     33077
#define ID_MAP_UNLINK                   33078
#define ID_MAP_AUTOLAYOUT               33079
#define ID_LATSTVALUES_USEMULTIPLIERS   33080
#define ID_OBJECT_POLL_INTERFACE_NAMES  33081
#define ID_POLLER_COPYTOCLIPBOARD       33082
#define ID_SITUATION_CREATE             33084
#define ID_SITUATION_EDIT               33085
#define ID_SITUATION_DELETE             33086
#define ID_SITUATION_CREATEINSTANCE     33087
#define ID_VIEW_SITUATIONS              33092
#define ID_CONTROLPANEL_EVENTCORRELATION 33093
#define ID_MAP_SHOWCONNECTORNAMES       33094
#define ID_CONTROLPANEL_NETWORKMAPS     33095
#define ID_MAP_CREATE                   33096
#define ID_MAP_DELETE                   33097
#define ID_MAP_ENSUREVISIBLE            33100
#define ID_MAP_RENAME                   33101
#define ID_CONTROLPANEL_SYSLOGPARSER    33103
#define ID_PARSER_SAVE                  33104
#define ID_ALWAYS_DISABLED              43210
#define IDS_GETFOLDERPATH_FAILED        61216
#define IDS_WORKDIR_CREATION_FAILED     61217
#define IDS_SCINTILLA_INIT_FAILED       61218

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        390
#define _APS_NEXT_COMMAND_VALUE         33105
#define _APS_NEXT_CONTROL_VALUE         1532
#define _APS_NEXT_SYMED_VALUE           135
#endif
#endif
