#
# Makefile.w32 - logwatch subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = logwatch
SOURCES = logwatch.cpp
SA_LIBS = -lnxlp -lnxdb

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
