package org.netxms.ui.eclipse.usermanager.reports.acl.constants;

public enum PermissionsSheetCells
{
   OBJECT_NAME,
   USER_OR_GROUP_NAME,
   INHERIT_ACCESS,
   READ,
   MODIFY,
   DELETE,
   CONTROL,
   MAINTENANCE,
   READ_AGENT,
   READ_SNMP,
   CREATE_CHILD_OBJECTS,
   VIEW_ALARMS,
   ACKNOWLEDGE_ALARMS,
   TERMINATE_ALARMS,
   ACCESS_CONTROL,
   CREATE_HELPDESK_ISSUES,
   DOWNLOAD_FILES,
   UPLOAD_FILES,
   MANAGE_FILES,
   SEND_EVENTS,
   PUSH_DATA,
   TAKE_SCREENSHOT,
   EDIT_MAINTENANCE_JOURNAL
}
