TARGET = netxms-base.jar
TYPE = jar
JAR_BUILD_MODE = install
MVNFLAGS = -Dmaven.test.skip=true -Ppkg-build
EXTERNAL_RESOURCES = ..\..\..\build\netxms-build-tag.properties

include ..\..\..\Makefile.inc.w32
