#
# Makefile for building NetXMS ecs Subagent for Novell NetWare platform
# Copyright (c) 2006 Victor Kirhenshtein
#

include ../../../../netware/Makefile.inc

OBJECTS  = ecs.o
EXEC     = ecs.nsm
DEF      = ecs.def

all: $(EXEC)

$(OBJECTS): Makefile.nw

.cpp.o:
	$(CC) $(CFLAGS) -o $*.o $<

$(EXEC): $(OBJECTS) $(DEF)
	$(LINK) $(LDFLAGS) -T $(DEF)
	cp ecs.nsm ../../../../netware/bin

clean:
	rm -f *.o $(EXEC)
