TARGET = nxzlib.dll
TYPE = dll
SOURCES= \
	adler32.c \
	compress.c \
	crc32.c \
	deflate.c \
	gzio.c \
	infback.c \
	inffast.c \
	inflate.c \
	inftrees.c \
	trees.c \
	uncompr.c \
	zutil.c

CPPFLAGS = /I ..
LDFLAGS = /DEF:..\nxzlib.def

!include ..\..\Makefile.inc.w32
