#
# Makefile.w32 - MariaDB database driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = mariadb
SOURCES = mariadb.cpp

DRV_CPPFLAGS = -I$(MARIADB_ROOT)/include
DRV_LIBS = $(MARIADB_LIBS)

include $(TOPDIR)/src/db/dbdrv/driver-common.mk
