#
# Makefile.w32 - snmptrap notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = snmptrap
SOURCES = $(wildcard *.cpp)
DRV_LIBS = -lnxjansson -lnxsnmp $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
