#!/bin/sh

print_header() {
	echo "" >> $CURRENT_LOG
	echo "********** $1 **********" >> $CURRENT_LOG
	echo "" >> $CURRENT_LOG
}

check_command() {
	command -v $1 >/dev/null 2>&1
	return $?
}

DIR=$(dirname "$0")

#check netxmsd, nxadm and nxagentd 

if [ ! -f $DIR/netxmsd ] || [ ! -f $DIR/nxadm ] || [ ! -f $DIR/nxagentd ]; then
    echo "Error: No netxms binaries found in current directory"
    exit 1
fi

#create folder

TS=`date +%Y%m%d-%H%M%S`
LOG_DIR=/tmp/netxms.info.$TS
mkdir $LOG_DIR

# Error log
ERROR_LOG=$LOG_DIR/stderr.txt


####################################
# OS level information:

OS_LOG=$LOG_DIR/os.txt
CURRENT_LOG=$OS_LOG

touch $OS_LOG

#Host name
print_header "Host name"
uname -a >> $OS_LOG
#OS version
print_header "OS version"
if check_command oslevel; then
    oslevel -s >> $OS_LOG 2>>$ERROR_LOG
fi
if check_command  machinfo; then
    machinfo >> $OS_LOG 2>>$ERROR_LOG
fi 
if check_command lsb_release; then
    lsb_release -idr >> $OS_LOG 2>>$ERROR_LOG
fi
if [ -f /etc/release ]; then
    cat /etc/release >> $OS_LOG 
fi

#Memory usage
print_header "Memory usage:"  
if check_command free; then
    free -m >> $OS_LOG 2>>$ERROR_LOG
fi
if check_command svmon; then
    svmon -P >> $OS_LOG 2>>$ERROR_LOG
fi
if check_command top; then
    top -b -n1 >> $OS_LOG 2>>$ERROR_LOG
    if [ $? -ne 0 ]; then
        top -b >> $OS_LOG 2>>$ERROR_LOG
    fi
fi

#Uptime
print_header "Uptime"
uptime >> $OS_LOG

#Process list
print_header "Process list"
ps -e >> $OS_LOG

#Open files (lsof output)
print_header "Open files"
if check_command pidof; then
    SERVER_PID=`pidof netxmsd`   
    AGENT_PID=`pidof nxagentd`   
elif check_command pgrep; then
    SERVER_PID=`pgrep -x netxmsd`
    AGENT_PID=`pgrep -x nxagentd`
else
    SERVER_PID=$(ps -eo pid,comm | awk '$2 == "netxmsd" {print $1}')
    SERVER_PID=$(ps -eo pid,comm | awk '$2 == "nxagentd" {print $1}')
fi

if check_command lsof; then
    lsof -p $SERVER_PID >> $OS_LOG 2>>$ERROR_LOG
    lsof -p $AGENT_PID >> $OS_LOG 2>>$ERROR_LOG
elif check_command pfiles; then
    pfiles $SERVER_PID >> $OS_LOG 2>>$ERROR_LOG
    pfiles $AGENT_PID >> $OS_LOG 2>>$ERROR_LOG
elif check_command procfiles; then
    procfiles $SERVER_PID >> $OS_LOG 2>>$ERROR_LOG
    procfiles $AGENT_PID >> $OS_LOG 2>>$ERROR_LOG
else
    if [ -f /proc/$SERVER_PID/fd ]; then
        ls -l /proc/$SERVER_PID/fd >> $OS_LOG 2>>$ERROR_LOG
    fi
    if [ -f /proc/$AGENT_PID/fd ]; then
        ls -l /proc/$AGENT_PID/fd >> $OS_LOG 2>>$ERROR_LOG
    fi    
fi

#interfaces ifconfig
print_header "Interfaces"
if check_command ifconfig; then
    ifconfig -a >> $OS_LOG
elif check_command ip; then
    ip address >> $OS_LOG
fi

# IP routes
print_header "IP routes"
if check_command route; then
    route -n >> $OS_LOG 2>>$ERROR_LOG
fi
if check_command netstat; then
    netstat -rn >> $OS_LOG 2>>$ERROR_LOG
fi

# ARP cache
print_header "ARP cache"
arp -a  >> $OS_LOG 2>>$ERROR_LOG


####################################
### Output of nxadm commands:

NXADM_LOG=$LOG_DIR/nxadm.txt
CURRENT_LOG=$NXADM_LOG

touch $NXADM_LOG

#debug
print_header "debug"
$DIR/nxadm -c "debug"  >> $NXADM_LOG
#show dbcp
print_header "show dbcp:"  >> $NXADM_LOG
$DIR/nxadm -c "show dbcp"  >> $NXADM_LOG
#show dbstats
print_header "show dbstats:"  >> $NXADM_LOG
$DIR/nxadm -c "show dbstats"  >> $NXADM_LOG
#show flags
print_header "show flags:"  >> $NXADM_LOG
$DIR/nxadm -c "show flags"  >> $NXADM_LOG
#show heap details
print_header "show heap details:"  >> $NXADM_LOG
$DIR/nxadm -c "show heap details"  >> $NXADM_LOG
#show heap summary
print_header "show heap summary:"  >> $NXADM_LOG
$DIR/nxadm -c "show heap summary"  >> $NXADM_LOG
#show index id
print_header "show index id:"  >> $NXADM_LOG
$DIR/nxadm -c "show index id"  >> $NXADM_LOG
#show index interface
print_header "show index interface:"  >> $NXADM_LOG
$DIR/nxadm -c "show index interface"  >> $NXADM_LOG
#show index nodeaddr
print_header "show index nodeaddr:"  >> $NXADM_LOG
$DIR/nxadm -c "show index nodeaddr"  >> $NXADM_LOG
#show index subnet
print_header "show index subnet:"  >> $NXADM_LOG
$DIR/nxadm -c "show index subnet"  >> $NXADM_LOG
#show index zone
print_header "show index zone:"  >> $NXADM_LOG
$DIR/nxadm -c "show index zone"  >> $NXADM_LOG
#show modules
print_header "show modules:"  >> $NXADM_LOG
$DIR/nxadm -c "show modules"  >> $NXADM_LOG
#show msgwq
print_header "show msgwq:"  >> $NXADM_LOG
$DIR/nxadm -c "show msgwq"  >> $NXADM_LOG
#show objects
print_header "show objects:"  >> $NXADM_LOG
$DIR/nxadm -c "show objects"  >> $NXADM_LOG
#show pe
print_header "show pe:"  >> $NXADM_LOG
$DIR/nxadm -c "show pe"  >> $NXADM_LOG
#show pollers
print_header "show pollers:"  >> $NXADM_LOG
$DIR/nxadm -c "show pollers"  >> $NXADM_LOG
#show queues
print_header "show queues:"  >> $NXADM_LOG
$DIR/nxadm -c "show queues"  >> $NXADM_LOG
#show sessions
print_header "show sessions:"  >> $NXADM_LOG
$DIR/nxadm -c "show sessions"  >> $NXADM_LOG
#show stats
print_header "show stats:"  >> $NXADM_LOG
$DIR/nxadm -c "show stats"  >> $NXADM_LOG
#show tunnels
print_header "show tunnels:"  >> $NXADM_LOG
$DIR/nxadm -c "show tunnels"  >> $NXADM_LOG
#show users
print_header "show users:"  >> $NXADM_LOG
$DIR/nxadm -c "show users"  >> $NXADM_LOG
#show watchdog
print_header "show watchdog:"  >> $NXADM_LOG
$DIR/nxadm -c "show watchdog"  >> $NXADM_LOG

#netxmsd, nxagentd log files
NETXMS_LOG=`$DIR/netxmsd -l | tail -1`
if [ "{syslog}" != "$NETXMS_LOG" ]; then
    cp $NETXMS_LOG $LOG_DIR/ 2>>$ERROR_LOG
else
    echo "Server log in syslog">>$ERROR_LOG
fi

NETXMS_LOG=`$DIR/nxagentd -l | tail -1`
if [ "{syslog}" != "$NETXMS_LOG" ]; then
    cp $NETXMS_LOG $LOG_DIR/ 2>>$ERROR_LOG
else
    echo "Agent log in syslog">>$ERROR_LOG
fi

#zipDeleteFolder
tar cf $LOG_DIR.tar $LOG_DIR 2>>$ERROR_LOG
gzip $LOG_DIR.tar
rm -rf $LOG_DIR

echo "Diagnostic file: $LOG_DIR.tar.gz"
