#
# Makefile.w32 - mssql subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = mssql
SOURCES = db.cpp main.cpp
SA_LIBS = -lnxdb $(PCRE_LIBS)

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
