#
# Makefile.w32 - websms notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = websms
SOURCES = $(wildcard *.cpp)
DRV_LIBS = $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
