#
# Makefile.w32 - wineventsync subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = wineventsync
SOURCES = reader.cpp wineventsync.cpp
SA_LIBS = -lwevtapi

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
