#
# Makefile.w32 - portech notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = portech
SOURCES = $(wildcard *.cpp)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
