#
# Makefile.w32 - test-physical-placement (physical placement property group unit tests)
# Part of NetXMS project
#

TOOL = test-physical-placement
SOURCES = test-physical-placement.cpp physical_placement.cpp
# physical_placement.cpp includes nxcore.h, which pulls in <microhttpd.h>
TOOL_CPPFLAGS = -I$(TOPDIR)/src/server/include -I$(TOPDIR)/tests/include -I$(MICROHTTPD_ROOT)/include -DNXCORE_EXPORTS
TOOL_LIBS = -lnxsrv -lnxsnmp -lnxsl -lnxdb -lnxagent -lnetxms -lnxjansson

vpath %.cpp $(TOPDIR)/src/server/core

include $(TOPDIR)/build/tool-common.mk
