//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by nxpc.rc
//
#define IDD_ABOUTBOX                    100
#define ID_CONNECT_TO_SERVER            101
#define IDS_EDIT                        102
#define ID_TREE_CTRL                    102
#define IDS_TOOL                        103
#define ID_LIST_CTRL                    103
#define IDM_MENU                        104
#define IDP_SOCKETS_INIT_FAILED         104
#define IDC_GRAPH                       104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDR_MAINFRAME                   128
#define IDS_NXC_INIT_FAILED             129
#define IDD_PROCESSING                  130
#define IDS_WORKDIR_CREATION_FAILED     130
#define IDI_CONNECT                     131
#define IDS_GETFOLDERPATH_FAILED        131
#define IDI_SEVERITY_MINOR              132
#define IDI_SEVERITY_NORMAL             133
#define IDI_SEVERITY_WARNING            134
#define IDI_ACK                         135
#define IDI_UNKNOWN                     136
#define IDI_SEVERITY_CRITICAL           137
#define IDI_SEVERITY_MAJOR              138
#define IDD_LOGIN                       139
#define IDI_LOGIN                       141
#define IDI_TEMPLATE_ROOT               142
#define IDI_CONTAINER                   143
#define IDI_NETWORK                     145
#define IDI_SERVICE                     146
#define IDI_NODE                        147
#define IDI_SUBNET                      148
#define IDI_TEMPLATE                    149
#define IDI_TEMPLATE_GROUP              150
#define IDI_INTERFACE                   151
#define IDM_CONTEXT                     160
#define IDD_EMPTY                       161
#define IDB_BTN_CLOSE                   163
#define IDB_BTN_CLOSE_DIS               164
#define IDB_BTN_PREV                    167
#define IDB_BTN_NEXT                    168
#define IDI_VPNC                        169
#define IDI_CLUSTER                     170
#define IDI_CONDITION                   171
#define IDI_OUTSTANDING                 172
#define IDC_INFO_TEXT                   1000
#define IDC_EDIT_SERVER                 1001
#define IDC_EDIT_LOGIN                  1002
#define IDC_EDIT_PASSWORD               1003
#define IDC_STATIC_TITLE                1005
#define IDC_CHECK_CACHE                 1006
#define IDC_STATIC_VERSION              1007
#define IDC_CHECK_PASSWORD              1008
#define ID_SYSTEM                       32771
#define IDS_CAP_SYSTEM                  32773
#define ID_SYSTEM_SETTINGS              32775
#define ID_VIEW                         32776
#define IDS_CAP_VIEW                    32778
#define ID_VIEW_ALARMS                  32779
#define ID_VIEW_NETWORKSUMMARY          32780
#define ID_VIEW_SUMMARY                 32780
#define IDS_CAP_CONNECT                 32782
#define ID_VIEW_OBJECTS                 32785
#define ID_VIEW_REFRESH                 32786
#define ID_BUTTON32787                  32787
#define ID_VIEW_REFRESH_ALL             32788
#define ID_ALARM                        32789
#define IDS_CAP_ALARM                   32791
#define ID_ALARM_ACKNOWLEDGE            32792
#define ID_ALARM_DELETE                 32793
#define ID_OBJECT                       32794
#define IDS_CAP_OBJECT                  32796
#define ID_OBJECT_DETAILS               32797
#define ID_OBJECT_LASTDCIVALUES         32798
#define ID_OBJECT_MANAGE                32799
#define ID_OBJECT_UNMANAGE              32800
#define IDS_CAP_REFRESH                 32802
#define ID_VIEW_CLOSE                   32805
#define ID_VIEW_PREV                    32808
#define ID_VIEW_NEXT                    32809
#define ID_OBJECT_WAKEUP                32810
#define ID_ALARM_SORTBY_SEVERITY        32811
#define ID_ALARM_SORTBY_SOURCE          32812
#define ID_ALARM_SORTBY_MESSAGETEXT     32813
#define ID_ALARM_SORTBY_TIMESTAMP       32814
#define ID_ALARM_SORTBY_ASCENDING       32815
#define ID_ALARM_SORTBY_DESCENDING      32816
#define ID_DCI                          32817
#define IDS_CAP_DCI                     32819
#define ID_DCI_SHOWHISTORY              32820
#define ID_DCI_GRAPH                    32821
#define ID_GRAPH                        32822
#define IDS_CAP_GRAPH                   32824
#define ID_GRAPH_PRESETS_LAST10MINUTES  32826
#define ID_GRAPH_PRESETS_LAST30MINUTES  32827
#define ID_GRAPH_PRESETS_LASTHOUR       32828
#define ID_GRAPH_PRESETS_LAST2HOURS     32829
#define ID_GRAPH_PRESETS_LAST4HOURS     32830
#define ID_GRAPH_PRESETS_LASTDAY        32831
#define ID_GRAPH_PRESETS_LASTWEEK       32832
#define ID_GRAPH_FULLSCREEN             32833
#define ID_GRAPH_PROPERTIES             32834
#define ID_VIEW_FULLSCREEN              32835
#define ID_ALARM_TERMINATE              32837
#define IDS_NEW                         65000
#define IDS_SUMMARY                     65000
#define IDS_FILE                        65001
#define IDS_ALARMS                      65001
#define IDS_MHELP                       65002
#define IDS_OBJECTS                     65002
#define IDS_SAVE                        65003
#define IDS_REFRESH                     65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_ABOUT                       65007

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1009
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
