TARGET = libpng.dll
TYPE = dll
SOURCES = filter_sse2_intrinsics.c intel_init.c \
          png.c pngerror.c pngget.c pngmem.c pngpread.c pngread.c \
          pngrio.c pngrtran.c pngrutil.c pngset.c pngtrans.c \
          pngwio.c pngwrite.c pngwtran.c pngwutil.c

CPPFLAGS = /I "$(NETXMS_BASE)\src\zlib" /DLIBPNG_EXPORTS /DPNG_BUILD_DLL /DPNG_INTEL_SSE
LIBS = nxzlib.lib

include ..\..\Makefile.inc.w32
