; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
#include "setup.iss"
OutputBaseFilename=nxagent-{#VersionString}-aarch64
ArchitecturesInstallIn64BitMode=arm64 
ArchitecturesAllowed=arm64 

[Files]
; Installer helpers
Source: "..\..\..\out\arm64\Release\bin\nxreload.exe"; DestDir: "{tmp}"; Flags: dontcopy signonce
; Agent
Source: "..\..\..\out\arm64\Release\bin\libethernetip.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnetxms.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxagent.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxdb.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxjava.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxlp.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxsde.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\libnxsnmp.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxagentd.exe"; DestDir: "{app}\bin"; BeforeInstall: RenameOldFile; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxcrashsrv.exe"; DestDir: "{app}\bin"; BeforeInstall: RenameOldFile; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxsagent.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\aifileops.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\bind9.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\db2.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\dbquery.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\devemu.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\entsoe.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\filemgr.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\informix.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\java.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\logwatch.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\mqtt.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\mssql.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\mysql.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\netsvc.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\openmeteo.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\oracle.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\pgsql.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\ping.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\prometheus.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\sms.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\ssh.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\tuxedo.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\ups.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\wineventsync.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\winnt.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\winperf.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\wmi.nsm"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\db2.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\informix.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\mariadb.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\mssql.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\mysql.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\odbc.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\oracle.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\..\out\arm64\Release\bin\pgsql.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\sqlite.ddr"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\contrib\nxagentd.conf-dist"; DestDir: "{app}\etc"; Flags: ignoreversion
Source: "..\..\..\out\arm64\Release\bin\nxpng.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxsqlite.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxjansson.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libc++.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libunwind.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libwinpthread-1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libjq-1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libonig-5.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libcurl.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libexpat-1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libnxmodbus-5.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libpcre-1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libpcre16-0.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libmicrohttpd-12.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libprotobuf.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libsnappy.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
;; NOT IMPLEMENTED ;; Source: "..\..\install\files\windows\arm64\smartctl.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\unzip.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\zlib1.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\capi.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libcrypto-3.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libmosquitto.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libssh.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\libssl-3.dll"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\openssl.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\install\files\windows\arm64\CRT\*"; DestDir: "{app}\bin"; Flags: ignoreversion
Source: "..\..\java-common\netxms-base\target\netxms-base-{#VersionString}.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
Source: "..\..\libnxjava\java\target\netxms-java-bridge-{#VersionString}.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
Source: "..\subagents\java\java\target\netxms-agent-{#VersionString}.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
Source: "..\subagents\jmx\target\jmx.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
Source: "..\subagents\opcua\target\opcua.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
Source: "..\subagents\ubntlw\target\ubntlw.jar"; DestDir: "{app}\lib\java"; Flags: ignoreversion
; Command-line tools
Source: "..\..\..\out\arm64\Release\bin\nxaevent.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxapush.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxcsum.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxethernetip.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxhwid.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxsnmpget.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxsnmpset.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxsnmpwalk.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\..\..\out\arm64\Release\bin\nxtftp.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce
Source: "..\tools\scripts\nxagentd-generate-tunnel-config.cmd"; DestDir: "{app}\bin"; Flags: ignoreversion
; User agent
Source: "..\..\..\out\arm64\Release\bin\nxuseragent.exe"; DestDir: "{app}\bin"; Flags: ignoreversion signonce

;#include "custom.iss"

#include "common.iss"

Function GetCustomCmdLine(Param: String): String;
Begin
  Result := '';
End;
