AppName=NetXMS Agent
AppVerName=NetXMS Agent 2.1.5
AppVersion=2.1.5
VersionInfoVersion=2.1.5
VersionInfoTextVersion=2.1.5
AppPublisher=Raden Solutions
AppPublisherURL=http://www.radensolutions.com
AppCopyright=© 2003-2019 Raden Solutions
AppSupportURL=http://www.netxms.org
AppUpdatesURL=http://www.netxms.org
DefaultDirName=C:\NetXMS
DefaultGroupName=NetXMS Agent
AllowNoIcons=yes
Compression=lzma
SolidCompression=yes
LanguageDetectionMethod=none
LicenseFile=..\..\..\copying
CloseApplications=no
SignTool=signtool
