#
# Makefile.w32 - ssh subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = ssh
SOURCES = channel_proxy.cpp handlers.cpp keys.cpp main.cpp session.cpp sp.cpp
SA_LIBS = $(LIBSSH_LIBS) $(PCRE_LIBS)
SA_CPPFLAGS = -I$(LIBSSH_ROOT)/include

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
