#
# Makefile for building NetXMS NetWare Subagent for Novell NetWare platform
# Copyright (c) 2004 Victor Kirhenshtein
#

include ../../../../netware/Makefile.inc

OBJECTS  = netware.o
EXEC     = netware.nsm
DEF      = netware.def

all: $(EXEC)

$(OBJECTS): Makefile.nw nwagent.h

.cpp.o:
	$(CC) $(CFLAGS) -o $*.o $<

$(EXEC): $(OBJECTS) $(DEF)
	$(LINK) $(LDFLAGS) -T $(DEF)
	cp netware.nsm ../../../../netware/bin

clean:
	rm -f *.o $(EXEC)
