#
# Makefile.w32 - aifileops subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = aifileops
SOURCES = aifileops.cpp file.cpp log.cpp patch.cpp
SA_LIBS = -lnxjansson $(PCRE_LIBS)

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
