#
# Makefile.w32 - MySQL database driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = mysql
SOURCES = mysql.cpp

DRV_CPPFLAGS = -I$(MYSQL_ROOT)/include
DRV_LIBS = $(MYSQL_LIBS)

include $(TOPDIR)/src/db/dbdrv/driver-common.mk
