TARGET = nxuseragent.exe
TYPE = exe
SUBSYSTEM = WINDOWS
SOURCES = appwnd.cpp comm.cpp config.cpp main.cpp menu.cpp net.cpp screenshot.cpp session.cpp tray.cpp

CPPFLAGS = /I$(NETXMS_BASE)\src\libpng
LIBS = libnetxms.lib libpng.lib ws2_32.lib gdi32.lib shell32.lib secur32.lib iphlpapi.lib wtsapi32.lib
	  
include ..\..\..\Makefile.inc.w32
