#
# Makefile.w32 - ups subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = ups
SOURCES = apc.cpp bcmxcp.cpp main.cpp megatec.cpp mec0003.cpp metasys.cpp microdowell.cpp serial.cpp ups.cpp usb.cpp
SA_LIBS = -lhid

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
