#
# Makefile.w32 - nxget (agent parameter query tool) for Windows/MinGW
# Part of NetXMS project
#

TOOL = nxget
SOURCES = nxget.cpp
TOOL_CPPFLAGS = -I$(TOPDIR)/src/server/include
TOOL_LIBS = -lnxsrv -lnetxms
# Entry point is wmain under UNICODE
TOOL_LDFLAGS = -municode

include $(TOPDIR)/build/tool-common.mk
