#
# Makefile.w32 - winnt subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = winnt
SOURCES = cpu.cpp disk.cpp fs.cpp hypervisor.cpp iostat.cpp main.cpp net.cpp procinfo.cpp prod.cpp registry.cpp system.cpp usb.cpp
SA_LIBS = -lntdll

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
