#
# Makefile.w32 - oxidized (Oxidized backup integration module) for Windows/MinGW
# Part of NetXMS project
#
# Note: this module has no MSVC project; sources are taken from Makefile.am.
# It exposes a REST API (api.cpp) via libmicrohttpd.
#

MODULE = oxidized
SOURCES = $(wildcard *.cpp)
MOD_LIBS = -lnxjansson $(CURL_LIBS) $(MICROHTTPD_LIBS)

include $(TOPDIR)/src/server/module-common.mk
