/* Generated by tools/generate_catalog.py - DO NOT EDIT BY HAND. */
/* ENTSO-E bidding-zone catalog snapshot: 2026-07-09 (entsoe-py master) */

struct BuiltinZone
{
   const char *name;
   const char *eic;
   const char *neighbours;   /* comma-separated zone names */
};

static const BuiltinZone s_builtinZones[] =
{
   { "AL", "10YAL-KESH-----5", "GR,ME,RS" },
   { "AT", "10YAT-APG------L", "CH,CZ,DE-LU,HU,IT-NORD,SI" },
   { "BA", "10YBA-JPCC-----D", "HR,ME,RS" },
   { "BE", "10YBE----------2", "DE-LU,FR,GB,NL" },
   { "BG", "10YCA-BULGARIA-R", "GR,MK,RO,RS,TR" },
   { "BY", "10Y1001A1001A51S", "LT" },
   { "CH", "10YCH-SWISSGRIDZ", "AT,DE-LU,FR,IT-NORD" },
   { "CZ", "10YCZ-CEPS-----N", "AT,DE-LU,PL,SK" },
   { "DE-LU", "10Y1001A1001A82H", "AT,BE,CH,CZ,DK-1,DK-2,FR,NL,NO-2,PL,SE-4" },
   { "DK-1", "10YDK-1--------W", "DE-LU,DK-2,GB,NL,NO-2,SE-3" },
   { "DK-2", "10YDK-2--------M", "DE-LU,DK-1,SE-4" },
   { "EE", "10Y1001A1001A39I", "FI,LV,RU" },
   { "ES", "10YES-REE------0", "FR,PT" },
   { "FI", "10YFI-1--------U", "EE,NO-4,RU,SE-1,SE-3" },
   { "FR", "10YFR-RTE------C", "BE,CH,DE-LU,ES,GB,IT-NORD" },
   { "GB", "10YGB----------A", "BE,DK-1,FR,IE-SEM,NL,NO-2" },
   { "GR", "10YGR-HTSO-----Y", "AL,BG,IT-BRNN,MK,TR" },
   { "HR", "10YHR-HEP------M", "BA,HU,RS,SI" },
   { "HU", "10YHU-MAVIR----U", "AT,HR,RO,RS,SI,SK,UA" },
   { "IE-SEM", "10Y1001A1001A59C", "GB" },
   { "IT-BRNN", "10Y1001A1001A699", "GR,IT-SUD" },
   { "IT-CALA", "10Y1001C--00096J", "IT-SICI,IT-SUD" },
   { "IT-CNOR", "10Y1001A1001A70O", "IT-CSUD,IT-NORD,IT-SARD" },
   { "IT-CSUD", "10Y1001A1001A71M", "IT-CNOR,IT-SARD,IT-SUD" },
   { "IT-FOGN", "10Y1001A1001A72K", "IT-SUD" },
   { "IT-NORD", "10Y1001A1001A73I", "AT,CH,FR,IT-CNOR,SI" },
   { "IT-ROSN", "10Y1001A1001A77A", "IT-SICI,IT-SUD" },
   { "IT-SARD", "10Y1001A1001A74G", "IT-CNOR,IT-CSUD" },
   { "IT-SICI", "10Y1001A1001A75E", "IT-CALA,IT-ROSN,MT" },
   { "IT-SUD", "10Y1001A1001A788", "IT-BRNN,IT-CALA,IT-CSUD,IT-FOGN,IT-ROSN" },
   { "LT", "10YLT-1001A0008Q", "BY,LV,PL,RU-KGD,SE-4" },
   { "LV", "10YLV-1001A00074", "EE,LT,RU" },
   { "ME", "10YCS-CG-TSO---S", "AL,BA,RS" },
   { "MK", "10YMK-MEPSO----8", "BG,GR,RS" },
   { "MT", "10Y1001A1001A93C", "IT-SICI" },
   { "NL", "10YNL----------L", "BE,DE-LU,DK-1,GB,NO-2" },
   { "NO-1", "10YNO-1--------2", "NO-2,NO-3,NO-5,SE-3" },
   { "NO-2", "10YNO-2--------T", "DE-LU,DK-1,GB,NL,NO-1,NO-5" },
   { "NO-3", "10YNO-3--------J", "NO-1,NO-4,NO-5,SE-2" },
   { "NO-4", "10YNO-4--------9", "FI,NO-3,SE-1,SE-2" },
   { "NO-5", "10Y1001A1001A48H", "NO-1,NO-2,NO-3" },
   { "PL", "10YPL-AREA-----S", "CZ,DE-LU,LT,SE-4,SK,UA" },
   { "PT", "10YPT-REN------W", "ES" },
   { "RO", "10YRO-TEL------P", "BG,HU,RS,UA" },
   { "RS", "10YCS-SERBIATSOV", "AL,BA,BG,HR,HU,ME,MK,RO" },
   { "RU", "10Y1001A1001A49F", "EE,FI,LV" },
   { "RU-KGD", "10Y1001A1001A50U", "LT" },
   { "SE-1", "10Y1001A1001A44P", "FI,NO-4,SE-2" },
   { "SE-2", "10Y1001A1001A45N", "NO-3,NO-4,SE-1,SE-3" },
   { "SE-3", "10Y1001A1001A46L", "DK-1,FI,NO-1,SE-2,SE-4" },
   { "SE-4", "10Y1001A1001A47J", "DE-LU,DK-2,LT,PL,SE-3" },
   { "SI", "10YSI-ELES-----O", "AT,HR,HU,IT-NORD" },
   { "SK", "10YSK-SEPS-----K", "CZ,HU,PL,UA" },
   { "TR", "10YTR-TEIAS----W", "BG,GR" },
   { "UA", "10Y1001C--00003F", "HU,PL,RO,SK" },
};

