/* 
 * IPFIX structs, types and definitions
 *
 * This is a generated file. Do not edit! 
 *
 */

/* ipfix information element list
 */
ipfix_field_type_t ipfix_field_types[] = {
   { 0, IPFIX_FT_OCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "octetDeltaCount", "" }, 
   { 0, IPFIX_FT_PACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "packetDeltaCount", "" }, 
   { 0, IPFIX_FT_FLOWS, 8, IPFIX_CODING_UINT, 
     "flows", "Netflow Number of Flows that were aggregated" }, 
   { 0, IPFIX_FT_PROTOCOLIDENTIFIER, 1, IPFIX_CODING_UINT, 
     "protocolIdentifier", "" }, 
   { 0, IPFIX_FT_IPCLASSOFSERVICE, 1, IPFIX_CODING_UINT, 
     "ipClassOfService", "" }, 
   { 0, IPFIX_FT_TCPCONTROLBITS, 1, IPFIX_CODING_UINT, 
     "tcpControlBits", "" }, 
   { 0, IPFIX_FT_SOURCETRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     "sourceTransportPort", "" }, 
   { 0, IPFIX_FT_SOURCEIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "sourceIPv4Address", "" }, 
   { 0, IPFIX_FT_SOURCEIPV4PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     "sourceIPv4PrefixLength", "" }, 
   { 0, IPFIX_FT_INGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
     "ingressInterface", "" }, 
   { 0, IPFIX_FT_DESTINATIONTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     "destinationTransportPort", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "destinationIPv4Address", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV4PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     "destinationIPv4PrefixLength", "" }, 
   { 0, IPFIX_FT_EGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
     "egressInterface", "" }, 
   { 0, IPFIX_FT_IPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "ipNextHopIPv4Address", "" }, 
   { 0, IPFIX_FT_BGPSOURCEASNUMBER, 4, IPFIX_CODING_UINT, 
     "bgpSourceAsNumber", "" }, 
   { 0, IPFIX_FT_BGPDESTINATIONASNUMBER, 4, IPFIX_CODING_UINT, 
     "bgpDestinationAsNumber", "" }, 
   { 0, IPFIX_FT_BGPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "bgpNextHopIPv4Address", "" }, 
   { 0, IPFIX_FT_POSTMCASTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "postMCastPacketDeltaCount", "" }, 
   { 0, IPFIX_FT_POSTMCASTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "postMCastOctetDeltaCount", "" }, 
   { 0, IPFIX_FT_FLOWENDSYSUPTIME, 4, IPFIX_CODING_UINT, 
     "flowEndSysUpTime", "" }, 
   { 0, IPFIX_FT_FLOWSTARTSYSUPTIME, 4, IPFIX_CODING_UINT, 
     "flowStartSysUpTime", "" }, 
   { 0, IPFIX_FT_POSTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "postOctetDeltaCount", "" }, 
   { 0, IPFIX_FT_POSTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "postPacketDeltaCount", "" }, 
   { 0, IPFIX_FT_MINIMUMIPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     "minimumIpTotalLength", "" }, 
   { 0, IPFIX_FT_MAXIMUMIPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     "maximumIpTotalLength", "" }, 
   { 0, IPFIX_FT_SOURCEIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "sourceIPv6Address", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "destinationIPv6Address", "" }, 
   { 0, IPFIX_FT_SOURCEIPV6PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     "sourceIPv6PrefixLength", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV6PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     "destinationIPv6PrefixLength", "" }, 
   { 0, IPFIX_FT_FLOWLABELIPV6, 4, IPFIX_CODING_UINT, 
     "flowLabelIPv6", "" }, 
   { 0, IPFIX_FT_ICMPTYPECODEIPV4, 2, IPFIX_CODING_UINT, 
     "icmpTypeCodeIPv4", "" }, 
   { 0, IPFIX_FT_IGMPTYPE, 1, IPFIX_CODING_UINT, 
     "igmpType", "" }, 
   { 0, IPFIX_FT_SAMPLING_INTERVAL, 4, IPFIX_CODING_UINT, 
     "sampling_interval", "Netflow Sampling Interval" }, 
   { 0, IPFIX_FT_SAMPLING_ALGORITHM, 1, IPFIX_CODING_UINT, 
     "sampling_algorithm", "Netflow Sampling Algorithm" }, 
   { 0, IPFIX_FT_FLOWACTIVETIMEOUT, 2, IPFIX_CODING_UINT, 
     "flowActiveTimeout", "" }, 
   { 0, IPFIX_FT_FLOWIDLETIMEOUT, 2, IPFIX_CODING_UINT, 
     "flowIdleTimeout", "" }, 
   { 0, IPFIX_FT_ENGINE_TYPE, 1, IPFIX_CODING_UINT, 
     "engine_type", "Netflow Engine Type" }, 
   { 0, IPFIX_FT_ENGINE_ID, 1, IPFIX_CODING_UINT, 
     "engine_id", "Netflow Engine ID" }, 
   { 0, IPFIX_FT_EXPORTEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "exportedOctetTotalCount", "" }, 
   { 0, IPFIX_FT_EXPORTEDMESSAGETOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "exportedMessageTotalCount", "" }, 
   { 0, IPFIX_FT_EXPORTEDFLOWRECORDTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "exportedFlowRecordTotalCount", "" }, 
   { 0, IPFIX_FT_SOURCEIPV4PREFIX, 4, IPFIX_CODING_IPADDR, 
     "sourceIPv4Prefix", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV4PREFIX, 4, IPFIX_CODING_IPADDR, 
     "destinationIPv4Prefix", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELTYPE, 1, IPFIX_CODING_UINT, 
     "mplsTopLabelType", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "mplsTopLabelIPv4Address", "" }, 
   { 0, IPFIX_FT_FLOW_SAMPLER_ID, 1, IPFIX_CODING_UINT, 
     "flow_sampler_id", "Netflow Flow Sampler ID" }, 
   { 0, IPFIX_FT_FLOW_SAMPLER_MODE, 1, IPFIX_CODING_UINT, 
     "flow_sampler_mode", "Netflow Flow Sampler Mode" }, 
   { 0, IPFIX_FT_FLOW_SAMPLER_RANDOM_INTERVAL, 4, IPFIX_CODING_UINT, 
     "flow_sampler_random_interval", "Netflow Packet Sample Interval" }, 
   { 0, IPFIX_FT_MINIMUMTTL, 1, IPFIX_CODING_UINT, 
     "minimumTTL", "" }, 
   { 0, IPFIX_FT_MAXIMUMTTL, 1, IPFIX_CODING_UINT, 
     "maximumTTL", "" }, 
   { 0, IPFIX_FT_FRAGMENTIDENTIFICATION, 4, IPFIX_CODING_UINT, 
     "fragmentIdentification", "" }, 
   { 0, IPFIX_FT_POSTIPCLASSOFSERVICE, 1, IPFIX_CODING_UINT, 
     "postIpClassOfService", "" }, 
   { 0, IPFIX_FT_SOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
     "sourceMacAddress", "" }, 
   { 0, IPFIX_FT_POSTDESTINATIONMACADDRESS, 6, IPFIX_CODING_BYTES, 
     "postDestinationMacAddress", "" }, 
   { 0, IPFIX_FT_VLANID, 2, IPFIX_CODING_UINT, 
     "vlanId", "" }, 
   { 0, IPFIX_FT_POSTVLANID, 2, IPFIX_CODING_UINT, 
     "postVlanId", "" }, 
   { 0, IPFIX_FT_IPVERSION, 1, IPFIX_CODING_UINT, 
     "ipVersion", "" }, 
   { 0, IPFIX_FT_FLOWDIRECTION, 1, IPFIX_CODING_UINT, 
     "flowDirection", "" }, 
   { 0, IPFIX_FT_IPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "ipNextHopIPv6Address", "" }, 
   { 0, IPFIX_FT_BGPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "bgpNextHopIPv6Address", "" }, 
   { 0, IPFIX_FT_IPV6EXTENSIONHEADERS, 4, IPFIX_CODING_UINT, 
     "ipv6ExtensionHeaders", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELSTACKSECTION, 65535, IPFIX_CODING_BYTES, 
     "mplsTopLabelStackSection", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION2, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection2", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION3, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection3", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION4, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection4", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION5, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection5", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION6, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection6", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION7, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection7", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION8, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection8", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION9, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection9", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION10, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection10", "" }, 
   { 0, IPFIX_FT_DESTINATIONMACADDRESS, 6, IPFIX_CODING_BYTES, 
     "destinationMacAddress", "" }, 
   { 0, IPFIX_FT_POSTSOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
     "postSourceMacAddress", "" }, 
   { 0, IPFIX_FT_OCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "octetTotalCount", "" }, 
   { 0, IPFIX_FT_PACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "packetTotalCount", "" }, 
   { 0, IPFIX_FT_FRAGMENTOFFSET, 2, IPFIX_CODING_UINT, 
     "fragmentOffset", "" }, 
   { 0, IPFIX_FT_MPLSVPNROUTEDISTINGUISHER, 65535, IPFIX_CODING_BYTES, 
     "mplsVpnRouteDistinguisher", "" }, 
   { 0, IPFIX_FT_BGPNEXTADJACENTASNUMBER, 4, IPFIX_CODING_UINT, 
     "bgpNextAdjacentAsNumber", "" }, 
   { 0, IPFIX_FT_BGPPREVADJACENTASNUMBER, 4, IPFIX_CODING_UINT, 
     "bgpPrevAdjacentAsNumber", "" }, 
   { 0, IPFIX_FT_EXPORTERIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "exporterIPv4Address", "" }, 
   { 0, IPFIX_FT_EXPORTERIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "exporterIPv6Address", "" }, 
   { 0, IPFIX_FT_DROPPEDOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "droppedOctetDeltaCount", "" }, 
   { 0, IPFIX_FT_DROPPEDPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     "droppedPacketDeltaCount", "" }, 
   { 0, IPFIX_FT_DROPPEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "droppedOctetTotalCount", "" }, 
   { 0, IPFIX_FT_DROPPEDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "droppedPacketTotalCount", "" }, 
   { 0, IPFIX_FT_FLOWENDREASON, 1, IPFIX_CODING_UINT, 
     "flowEndReason", "" }, 
   { 0, IPFIX_FT_COMMONPROPERTIESID, 8, IPFIX_CODING_UINT, 
     "commonPropertiesId", "" }, 
   { 0, IPFIX_FT_OBSERVATIONPOINTID, 4, IPFIX_CODING_UINT, 
     "observationPointId", "" }, 
   { 0, IPFIX_FT_ICMPTYPECODEIPV6, 2, IPFIX_CODING_UINT, 
     "icmpTypeCodeIPv6", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "mplsTopLabelIPv6Address", "" }, 
   { 0, IPFIX_FT_LINECARDID, 4, IPFIX_CODING_UINT, 
     "lineCardId", "" }, 
   { 0, IPFIX_FT_PORTID, 4, IPFIX_CODING_UINT, 
     "portId", "" }, 
   { 0, IPFIX_FT_METERINGPROCESSID, 4, IPFIX_CODING_UINT, 
     "meteringProcessId", "" }, 
   { 0, IPFIX_FT_EXPORTINGPROCESSID, 4, IPFIX_CODING_UINT, 
     "exportingProcessId", "" }, 
   { 0, IPFIX_FT_TEMPLATEID, 2, IPFIX_CODING_UINT, 
     "templateId", "" }, 
   { 0, IPFIX_FT_WLANCHANNELID, 1, IPFIX_CODING_UINT, 
     "wlanChannelId", "" }, 
   { 0, IPFIX_FT_WLANSSID, 65535, IPFIX_CODING_STRING, 
     "wlanSSID", "" }, 
   { 0, IPFIX_FT_FLOWID, 8, IPFIX_CODING_UINT, 
     "flowId", "" }, 
   { 0, IPFIX_FT_OBSERVATIONDOMAINID, 4, IPFIX_CODING_UINT, 
     "observationDomainId", "" }, 
   { 0, IPFIX_FT_FLOWSTARTSECONDS, 4, IPFIX_CODING_UINT, 
     "flowStartSeconds", "" }, 
   { 0, IPFIX_FT_FLOWENDSECONDS, 4, IPFIX_CODING_UINT, 
     "flowEndSeconds", "" }, 
   { 0, IPFIX_FT_FLOWSTARTMILLISECONDS, 8, IPFIX_CODING_UINT, 
     "flowStartMilliseconds", "" }, 
   { 0, IPFIX_FT_FLOWENDMILLISECONDS, 8, IPFIX_CODING_UINT, 
     "flowEndMilliseconds", "" }, 
   { 0, IPFIX_FT_FLOWSTARTMICROSECONDS, 8, IPFIX_CODING_NTP, 
     "flowStartMicroseconds", "" }, 
   { 0, IPFIX_FT_FLOWENDMICROSECONDS, 8, IPFIX_CODING_NTP, 
     "flowEndMicroseconds", "" }, 
   { 0, IPFIX_FT_FLOWSTARTNANOSECONDS, 8, IPFIX_CODING_NTP, 
     "flowStartNanoseconds", "" }, 
   { 0, IPFIX_FT_FLOWENDNANOSECONDS, 8, IPFIX_CODING_NTP, 
     "flowEndNanoseconds", "" }, 
   { 0, IPFIX_FT_FLOWSTARTDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
     "flowStartDeltaMicroseconds", "" }, 
   { 0, IPFIX_FT_FLOWENDDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
     "flowEndDeltaMicroseconds", "" }, 
   { 0, IPFIX_FT_SYSTEMINITTIMEMILLISECONDS, 8, IPFIX_CODING_UINT, 
     "systemInitTimeMilliseconds", "" }, 
   { 0, IPFIX_FT_FLOWDURATIONMILLISECONDS, 4, IPFIX_CODING_UINT, 
     "flowDurationMilliseconds", "" }, 
   { 0, IPFIX_FT_FLOWDURATIONMICROSECONDS, 4, IPFIX_CODING_UINT, 
     "flowDurationMicroseconds", "" }, 
   { 0, IPFIX_FT_OBSERVEDFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "observedFlowTotalCount", "" }, 
   { 0, IPFIX_FT_IGNOREDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "ignoredPacketTotalCount", "" }, 
   { 0, IPFIX_FT_IGNOREDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "ignoredOctetTotalCount", "" }, 
   { 0, IPFIX_FT_NOTSENTFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "notSentFlowTotalCount", "" }, 
   { 0, IPFIX_FT_NOTSENTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "notSentPacketTotalCount", "" }, 
   { 0, IPFIX_FT_NOTSENTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "notSentOctetTotalCount", "" }, 
   { 0, IPFIX_FT_DESTINATIONIPV6PREFIX, 16, IPFIX_CODING_IPADDR, 
     "destinationIPv6Prefix", "" }, 
   { 0, IPFIX_FT_SOURCEIPV6PREFIX, 16, IPFIX_CODING_IPADDR, 
     "sourceIPv6Prefix", "" }, 
   { 0, IPFIX_FT_POSTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "postOctetTotalCount", "" }, 
   { 0, IPFIX_FT_POSTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "postPacketTotalCount", "" }, 
   { 0, IPFIX_FT_FLOWKEYINDICATOR, 8, IPFIX_CODING_UINT, 
     "flowKeyIndicator", "" }, 
   { 0, IPFIX_FT_POSTMCASTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "postMCastPacketTotalCount", "" }, 
   { 0, IPFIX_FT_POSTMCASTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "postMCastOctetTotalCount", "" }, 
   { 0, IPFIX_FT_ICMPTYPEIPV4, 1, IPFIX_CODING_UINT, 
     "icmpTypeIPv4", "" }, 
   { 0, IPFIX_FT_ICMPCODEIPV4, 1, IPFIX_CODING_UINT, 
     "icmpCodeIPv4", "" }, 
   { 0, IPFIX_FT_ICMPTYPEIPV6, 1, IPFIX_CODING_UINT, 
     "icmpTypeIPv6", "" }, 
   { 0, IPFIX_FT_ICMPCODEIPV6, 1, IPFIX_CODING_UINT, 
     "icmpCodeIPv6", "" }, 
   { 0, IPFIX_FT_UDPSOURCEPORT, 2, IPFIX_CODING_UINT, 
     "udpSourcePort", "" }, 
   { 0, IPFIX_FT_UDPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
     "udpDestinationPort", "" }, 
   { 0, IPFIX_FT_TCPSOURCEPORT, 2, IPFIX_CODING_UINT, 
     "tcpSourcePort", "" }, 
   { 0, IPFIX_FT_TCPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
     "tcpDestinationPort", "" }, 
   { 0, IPFIX_FT_TCPSEQUENCENUMBER, 4, IPFIX_CODING_UINT, 
     "tcpSequenceNumber", "" }, 
   { 0, IPFIX_FT_TCPACKNOWLEDGEMENTNUMBER, 4, IPFIX_CODING_UINT, 
     "tcpAcknowledgementNumber", "" }, 
   { 0, IPFIX_FT_TCPWINDOWSIZE, 2, IPFIX_CODING_UINT, 
     "tcpWindowSize", "" }, 
   { 0, IPFIX_FT_TCPURGENTPOINTER, 2, IPFIX_CODING_UINT, 
     "tcpUrgentPointer", "" }, 
   { 0, IPFIX_FT_TCPHEADERLENGTH, 1, IPFIX_CODING_UINT, 
     "tcpHeaderLength", "" }, 
   { 0, IPFIX_FT_IPHEADERLENGTH, 1, IPFIX_CODING_UINT, 
     "ipHeaderLength", "" }, 
   { 0, IPFIX_FT_TOTALLENGTHIPV4, 2, IPFIX_CODING_UINT, 
     "totalLengthIPv4", "" }, 
   { 0, IPFIX_FT_PAYLOADLENGTHIPV6, 2, IPFIX_CODING_UINT, 
     "payloadLengthIPv6", "" }, 
   { 0, IPFIX_FT_IPTTL, 1, IPFIX_CODING_UINT, 
     "ipTTL", "" }, 
   { 0, IPFIX_FT_NEXTHEADERIPV6, 1, IPFIX_CODING_UINT, 
     "nextHeaderIPv6", "" }, 
   { 0, IPFIX_FT_MPLSPAYLOADLENGTH, 4, IPFIX_CODING_UINT, 
     "mplsPayloadLength", "" }, 
   { 0, IPFIX_FT_IPDIFFSERVCODEPOINT, 1, IPFIX_CODING_UINT, 
     "ipDiffServCodePoint", "" }, 
   { 0, IPFIX_FT_IPPRECEDENCE, 1, IPFIX_CODING_UINT, 
     "ipPrecedence", "" }, 
   { 0, IPFIX_FT_FRAGMENTFLAGS, 1, IPFIX_CODING_UINT, 
     "fragmentFlags", "" }, 
   { 0, IPFIX_FT_OCTETDELTASUMOFSQUARES, 8, IPFIX_CODING_UINT, 
     "octetDeltaSumOfSquares", "" }, 
   { 0, IPFIX_FT_OCTETTOTALSUMOFSQUARES, 8, IPFIX_CODING_UINT, 
     "octetTotalSumOfSquares", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELTTL, 1, IPFIX_CODING_UINT, 
     "mplsTopLabelTTL", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKLENGTH, 4, IPFIX_CODING_UINT, 
     "mplsLabelStackLength", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKDEPTH, 4, IPFIX_CODING_UINT, 
     "mplsLabelStackDepth", "" }, 
   { 0, IPFIX_FT_MPLSTOPLABELEXP, 1, IPFIX_CODING_UINT, 
     "mplsTopLabelExp", "" }, 
   { 0, IPFIX_FT_IPPAYLOADLENGTH, 4, IPFIX_CODING_UINT, 
     "ipPayloadLength", "" }, 
   { 0, IPFIX_FT_UDPMESSAGELENGTH, 2, IPFIX_CODING_UINT, 
     "udpMessageLength", "" }, 
   { 0, IPFIX_FT_ISMULTICAST, 1, IPFIX_CODING_UINT, 
     "isMulticast", "" }, 
   { 0, IPFIX_FT_IPV4IHL, 1, IPFIX_CODING_UINT, 
     "ipv4IHL", "" }, 
   { 0, IPFIX_FT_IPV4OPTIONS, 4, IPFIX_CODING_UINT, 
     "ipv4Options", "" }, 
   { 0, IPFIX_FT_TCPOPTIONS, 8, IPFIX_CODING_UINT, 
     "tcpOptions", "" }, 
   { 0, IPFIX_FT_PADDINGOCTETS, 65535, IPFIX_CODING_BYTES, 
     "paddingOctets", "" }, 
   { 0, IPFIX_FT_COLLECTORIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     "collectorIPv4Address", "" }, 
   { 0, IPFIX_FT_COLLECTORIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     "collectorIPv6Address", "" }, 
   { 0, IPFIX_FT_COLLECTORINTERFACE, 4, IPFIX_CODING_UINT, 
     "collectorInterface", "" }, 
   { 0, IPFIX_FT_COLLECTORPROTOCOLVERSION, 1, IPFIX_CODING_UINT, 
     "collectorProtocolVersion", "" }, 
   { 0, IPFIX_FT_COLLECTORTRANSPORTPROTOCOL, 1, IPFIX_CODING_UINT, 
     "collectorTransportProtocol", "" }, 
   { 0, IPFIX_FT_COLLECTORTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     "collectorTransportPort", "" }, 
   { 0, IPFIX_FT_EXPORTERTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     "exporterTransportPort", "" }, 
   { 0, IPFIX_FT_TCPSYNTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpSynTotalCount", "" }, 
   { 0, IPFIX_FT_TCPFINTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpFinTotalCount", "" }, 
   { 0, IPFIX_FT_TCPRSTTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpRstTotalCount", "" }, 
   { 0, IPFIX_FT_TCPPSHTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpPshTotalCount", "" }, 
   { 0, IPFIX_FT_TCPACKTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpAckTotalCount", "" }, 
   { 0, IPFIX_FT_TCPURGTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     "tcpUrgTotalCount", "" }, 
   { 0, IPFIX_FT_IPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     "ipTotalLength", "" }, 
   { 0, IPFIX_FT_POSTMPLSTOPLABELEXP, 1, IPFIX_CODING_UINT, 
     "postMplsTopLabelExp", "" }, 
   { 0, IPFIX_FT_TCPWINDOWSCALE, 2, IPFIX_CODING_UINT, 
     "tcpWindowScale", "" }, 
   { 0, IPFIX_FT_OBSERVATIONPOINTID_PSAMP, 8, IPFIX_CODING_UINT, 
     "observationPointId_PSAMP", "" }, 
   { 0, IPFIX_FT_SELECTIONSEQUENCEID, 8, IPFIX_CODING_UINT, 
     "selectionSequenceId", "" }, 
   { 0, IPFIX_FT_SELECTORID, 2, IPFIX_CODING_UINT, 
     "selectorId", "" }, 
   { 0, IPFIX_FT_INFORMATIONELEMENTID, 2, IPFIX_CODING_UINT, 
     "informationElementId", "" }, 
   { 0, IPFIX_FT_SELECTORALGORITHM, 2, IPFIX_CODING_UINT, 
     "selectorAlgorithm", "" }, 
   { 0, IPFIX_FT_SAMPLINGPACKETINTERVAL, 4, IPFIX_CODING_UINT, 
     "samplingPacketInterval", "" }, 
   { 0, IPFIX_FT_SAMPLINGPACKETSPACE, 4, IPFIX_CODING_UINT, 
     "samplingPacketSpace", "" }, 
   { 0, IPFIX_FT_SAMPLINGTIMEINTERVAL, 8, IPFIX_CODING_NTP, 
     "samplingTimeInterval", "" }, 
   { 0, IPFIX_FT_SAMPLINGTIMESPACE, 8, IPFIX_CODING_NTP, 
     "samplingTimeSpace", "" }, 
   { 0, IPFIX_FT_SAMPLINGSIZE, 4, IPFIX_CODING_UINT, 
     "samplingSize", "" }, 
   { 0, IPFIX_FT_SAMPLINGPOPULATION, 4, IPFIX_CODING_UINT, 
     "samplingPopulation", "" }, 
   { 0, IPFIX_FT_SAMPLINGPROBABILITY, 8, IPFIX_CODING_FLOAT, 
     "samplingProbability", "" }, 
   { 0, IPFIX_FT_DATALINKFRAMESIZE, 4, IPFIX_CODING_UINT, 
     "dataLinkFrameSize", "" }, 
   { 0, IPFIX_FT_IPHEADERPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     "ipHeaderPacketSection", "" }, 
   { 0, IPFIX_FT_IPPAYLOADPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     "ipPayloadPacketSection", "" }, 
   { 0, IPFIX_FT_DATALINKFRAMESECTION, 65535, IPFIX_CODING_BYTES, 
     "dataLinkFrameSection", "" }, 
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION, 65535, IPFIX_CODING_BYTES, 
     "mplsLabelStackSection", "" }, 
   { 0, IPFIX_FT_MPLSPAYLOADPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     "mplsPayloadPacketSection", "" }, 
   { 0, IPFIX_FT_PACKETSOBSERVED, 8, IPFIX_CODING_UINT, 
     "packetsObserved", "" }, 
   { 0, IPFIX_FT_PACKETSSELECTED, 8, IPFIX_CODING_UINT, 
     "packetsSelected", "" }, 
   { 0, IPFIX_FT_FIXEDERROR, 8, IPFIX_CODING_FLOAT, 
     "fixedError", "" }, 
   { 0, IPFIX_FT_RELATIVEERROR, 8, IPFIX_CODING_FLOAT, 
     "relativeError", "" }, 
   { 0, IPFIX_FT_OBSERVATIONTIMESECONDS, 4, IPFIX_CODING_UINT, 
     "observationTimeSeconds", "" }, 
   { 0, IPFIX_FT_OBSERVATIONTIMEMILLISECONDS, 8, IPFIX_CODING_UINT, 
     "observationTimeMilliseconds", "" }, 
   { 0, IPFIX_FT_OBSERVATIONTIMEMICROSECONDS, 8, IPFIX_CODING_NTP, 
     "observationTimeMicroseconds", "" }, 
   { 0, IPFIX_FT_OBSERVATIONTIMENANOSECONDS, 8, IPFIX_CODING_NTP, 
     "observationTimeNanoseconds", "" }, 
   { 0, IPFIX_FT_DIGESTHASHVALUE, 8, IPFIX_CODING_UINT, 
     "digestHashValue", "" }, 
   { 0, IPFIX_FT_HASHIPPAYLOADOFFSET, 8, IPFIX_CODING_UINT, 
     "hashIPPayloadOffset", "" }, 
   { 0, IPFIX_FT_HASHIPPAYLOADSIZE, 8, IPFIX_CODING_UINT, 
     "hashIPPayloadSize", "" }, 
   { 0, IPFIX_FT_HASHOUTPUTRANGEMIN, 8, IPFIX_CODING_UINT, 
     "hashOutputRangeMin", "" }, 
   { 0, IPFIX_FT_HASHOUTPUTRANGEMAX, 8, IPFIX_CODING_UINT, 
     "hashOutputRangeMax", "" }, 
   { 0, IPFIX_FT_HASHSELECTEDRANGEMIN, 8, IPFIX_CODING_UINT, 
     "hashSelectedRangeMin", "" }, 
   { 0, IPFIX_FT_HASHSELECTEDRANGEMAX, 8, IPFIX_CODING_UINT, 
     "hashSelectedRangeMax", "" }, 
   { 0, IPFIX_FT_HASHDIGESTOUTPUT, 1, IPFIX_CODING_BYTES, 
     "hashDigestOutput", "" }, 
   { 0, IPFIX_FT_HASHINITIALISERVALUE, 8, IPFIX_CODING_UINT, 
     "hashInitialiserValue", "" }, 
   { 0, 0, -1, 0, NULL, NULL, }
};
