/* 
 * IPFIX structs, types and definitions
 *
 * This is a generated file. Do not edit! 
 *
 */

/* ipfix information element list
 */
ipfix_field_type_t ipfix_field_types[] = {
   { 0, IPFIX_FT_OCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"octetDeltaCount", (char*)"" },
   { 0, IPFIX_FT_PACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"packetDeltaCount", (char*)"" },
   { 0, IPFIX_FT_FLOWS, 8, IPFIX_CODING_UINT, 
     (char*)"flows", (char*)"Netflow Number of Flows that were aggregated" },
   { 0, IPFIX_FT_PROTOCOLIDENTIFIER, 1, IPFIX_CODING_UINT, 
     (char*)"protocolIdentifier", (char*)"" },
   { 0, IPFIX_FT_IPCLASSOFSERVICE, 1, IPFIX_CODING_UINT, 
     (char*)"ipClassOfService", (char*)"" },
   { 0, IPFIX_FT_TCPCONTROLBITS, 1, IPFIX_CODING_UINT, 
     (char*)"tcpControlBits", (char*)"" },
   { 0, IPFIX_FT_SOURCETRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     (char*)"sourceTransportPort", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"sourceIPv4Address", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV4PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"sourceIPv4PrefixLength", (char*)"" },
   { 0, IPFIX_FT_INGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
     (char*)"ingressInterface", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     (char*)"destinationTransportPort", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"destinationIPv4Address", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV4PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"destinationIPv4PrefixLength", (char*)"" },
   { 0, IPFIX_FT_EGRESSINTERFACE, 4, IPFIX_CODING_UINT, 
     (char*)"egressInterface", (char*)"" },
   { 0, IPFIX_FT_IPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"ipNextHopIPv4Address", (char*)"" },
   { 0, IPFIX_FT_BGPSOURCEASNUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"bgpSourceAsNumber", (char*)"" },
   { 0, IPFIX_FT_BGPDESTINATIONASNUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"bgpDestinationAsNumber", (char*)"" },
   { 0, IPFIX_FT_BGPNEXTHOPIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"bgpNextHopIPv4Address", (char*)"" },
   { 0, IPFIX_FT_POSTMCASTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postMCastPacketDeltaCount", (char*)"" },
   { 0, IPFIX_FT_POSTMCASTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postMCastOctetDeltaCount", (char*)"" },
   { 0, IPFIX_FT_FLOWENDSYSUPTIME, 4, IPFIX_CODING_UINT, 
     (char*)"flowEndSysUpTime", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTSYSUPTIME, 4, IPFIX_CODING_UINT, 
     (char*)"flowStartSysUpTime", (char*)"" },
   { 0, IPFIX_FT_POSTOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postOctetDeltaCount", (char*)"" },
   { 0, IPFIX_FT_POSTPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postPacketDeltaCount", (char*)"" },
   { 0, IPFIX_FT_MINIMUMIPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     (char*)"minimumIpTotalLength", (char*)"" },
   { 0, IPFIX_FT_MAXIMUMIPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     (char*)"maximumIpTotalLength", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"sourceIPv6Address", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"destinationIPv6Address", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV6PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"sourceIPv6PrefixLength", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV6PREFIXLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"destinationIPv6PrefixLength", (char*)"" },
   { 0, IPFIX_FT_FLOWLABELIPV6, 4, IPFIX_CODING_UINT, 
     (char*)"flowLabelIPv6", (char*)"" },
   { 0, IPFIX_FT_ICMPTYPECODEIPV4, 2, IPFIX_CODING_UINT, 
     (char*)"icmpTypeCodeIPv4", (char*)"" },
   { 0, IPFIX_FT_IGMPTYPE, 1, IPFIX_CODING_UINT, 
     (char*)"igmpType", (char*)"" },
   { 0, IPFIX_FT_SAMPLING_INTERVAL, 4, IPFIX_CODING_UINT, 
     (char*)"sampling_interval", (char*)"Netflow Sampling Interval" },
   { 0, IPFIX_FT_SAMPLING_ALGORITHM, 1, IPFIX_CODING_UINT, 
     (char*)"sampling_algorithm", (char*)"Netflow Sampling Algorithm" },
   { 0, IPFIX_FT_FLOWACTIVETIMEOUT, 2, IPFIX_CODING_UINT, 
     (char*)"flowActiveTimeout", (char*)"" },
   { 0, IPFIX_FT_FLOWIDLETIMEOUT, 2, IPFIX_CODING_UINT, 
     (char*)"flowIdleTimeout", (char*)"" },
   { 0, IPFIX_FT_ENGINE_TYPE, 1, IPFIX_CODING_UINT, 
     (char*)"engine_type", (char*)"Netflow Engine Type" },
   { 0, IPFIX_FT_ENGINE_ID, 1, IPFIX_CODING_UINT, 
     (char*)"engine_id", (char*)"Netflow Engine ID" },
   { 0, IPFIX_FT_EXPORTEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"exportedOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_EXPORTEDMESSAGETOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"exportedMessageTotalCount", (char*)"" },
   { 0, IPFIX_FT_EXPORTEDFLOWRECORDTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"exportedFlowRecordTotalCount", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV4PREFIX, 4, IPFIX_CODING_IPADDR, 
     (char*)"sourceIPv4Prefix", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV4PREFIX, 4, IPFIX_CODING_IPADDR, 
     (char*)"destinationIPv4Prefix", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELTYPE, 1, IPFIX_CODING_UINT, 
     (char*)"mplsTopLabelType", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"mplsTopLabelIPv4Address", (char*)"" },
   { 0, IPFIX_FT_FLOW_SAMPLER_ID, 1, IPFIX_CODING_UINT, 
     (char*)"flow_sampler_id", (char*)"Netflow Flow Sampler ID" },
   { 0, IPFIX_FT_FLOW_SAMPLER_MODE, 1, IPFIX_CODING_UINT, 
     (char*)"flow_sampler_mode", (char*)"Netflow Flow Sampler Mode" },
   { 0, IPFIX_FT_FLOW_SAMPLER_RANDOM_INTERVAL, 4, IPFIX_CODING_UINT, 
     (char*)"flow_sampler_random_interval", (char*)"Netflow Packet Sample Interval" },
   { 0, IPFIX_FT_MINIMUMTTL, 1, IPFIX_CODING_UINT, 
     (char*)"minimumTTL", (char*)"" },
   { 0, IPFIX_FT_MAXIMUMTTL, 1, IPFIX_CODING_UINT, 
     (char*)"maximumTTL", (char*)"" },
   { 0, IPFIX_FT_FRAGMENTIDENTIFICATION, 4, IPFIX_CODING_UINT, 
     (char*)"fragmentIdentification", (char*)"" },
   { 0, IPFIX_FT_POSTIPCLASSOFSERVICE, 1, IPFIX_CODING_UINT, 
     (char*)"postIpClassOfService", (char*)"" },
   { 0, IPFIX_FT_SOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
     (char*)"sourceMacAddress", (char*)"" },
   { 0, IPFIX_FT_POSTDESTINATIONMACADDRESS, 6, IPFIX_CODING_BYTES, 
     (char*)"postDestinationMacAddress", (char*)"" },
   { 0, IPFIX_FT_VLANID, 2, IPFIX_CODING_UINT, 
     (char*)"vlanId", (char*)"" },
   { 0, IPFIX_FT_POSTVLANID, 2, IPFIX_CODING_UINT, 
     (char*)"postVlanId", (char*)"" },
   { 0, IPFIX_FT_IPVERSION, 1, IPFIX_CODING_UINT, 
     (char*)"ipVersion", (char*)"" },
   { 0, IPFIX_FT_FLOWDIRECTION, 1, IPFIX_CODING_UINT, 
     (char*)"flowDirection", (char*)"" },
   { 0, IPFIX_FT_IPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"ipNextHopIPv6Address", (char*)"" },
   { 0, IPFIX_FT_BGPNEXTHOPIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"bgpNextHopIPv6Address", (char*)"" },
   { 0, IPFIX_FT_IPV6EXTENSIONHEADERS, 4, IPFIX_CODING_UINT, 
     (char*)"ipv6ExtensionHeaders", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELSTACKSECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsTopLabelStackSection", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION2, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection2", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION3, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection3", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION4, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection4", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION5, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection5", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION6, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection6", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION7, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection7", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION8, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection8", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION9, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection9", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION10, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection10", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONMACADDRESS, 6, IPFIX_CODING_BYTES, 
     (char*)"destinationMacAddress", (char*)"" },
   { 0, IPFIX_FT_POSTSOURCEMACADDRESS, 6, IPFIX_CODING_BYTES, 
     (char*)"postSourceMacAddress", (char*)"" },
   { 0, IPFIX_FT_OCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"octetTotalCount", (char*)"" },
   { 0, IPFIX_FT_PACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"packetTotalCount", (char*)"" },
   { 0, IPFIX_FT_FRAGMENTOFFSET, 2, IPFIX_CODING_UINT, 
     (char*)"fragmentOffset", (char*)"" },
   { 0, IPFIX_FT_MPLSVPNROUTEDISTINGUISHER, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsVpnRouteDistinguisher", (char*)"" },
   { 0, IPFIX_FT_BGPNEXTADJACENTASNUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"bgpNextAdjacentAsNumber", (char*)"" },
   { 0, IPFIX_FT_BGPPREVADJACENTASNUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"bgpPrevAdjacentAsNumber", (char*)"" },
   { 0, IPFIX_FT_EXPORTERIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"exporterIPv4Address", (char*)"" },
   { 0, IPFIX_FT_EXPORTERIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"exporterIPv6Address", (char*)"" },
   { 0, IPFIX_FT_DROPPEDOCTETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"droppedOctetDeltaCount", (char*)"" },
   { 0, IPFIX_FT_DROPPEDPACKETDELTACOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"droppedPacketDeltaCount", (char*)"" },
   { 0, IPFIX_FT_DROPPEDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"droppedOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_DROPPEDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"droppedPacketTotalCount", (char*)"" },
   { 0, IPFIX_FT_FLOWENDREASON, 1, IPFIX_CODING_UINT, 
     (char*)"flowEndReason", (char*)"" },
   { 0, IPFIX_FT_COMMONPROPERTIESID, 8, IPFIX_CODING_UINT, 
     (char*)"commonPropertiesId", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONPOINTID, 4, IPFIX_CODING_UINT, 
     (char*)"observationPointId", (char*)"" },
   { 0, IPFIX_FT_ICMPTYPECODEIPV6, 2, IPFIX_CODING_UINT, 
     (char*)"icmpTypeCodeIPv6", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"mplsTopLabelIPv6Address", (char*)"" },
   { 0, IPFIX_FT_LINECARDID, 4, IPFIX_CODING_UINT, 
     (char*)"lineCardId", (char*)"" },
   { 0, IPFIX_FT_PORTID, 4, IPFIX_CODING_UINT, 
     (char*)"portId", (char*)"" },
   { 0, IPFIX_FT_METERINGPROCESSID, 4, IPFIX_CODING_UINT, 
     (char*)"meteringProcessId", (char*)"" },
   { 0, IPFIX_FT_EXPORTINGPROCESSID, 4, IPFIX_CODING_UINT, 
     (char*)"exportingProcessId", (char*)"" },
   { 0, IPFIX_FT_TEMPLATEID, 2, IPFIX_CODING_UINT, 
     (char*)"templateId", (char*)"" },
   { 0, IPFIX_FT_WLANCHANNELID, 1, IPFIX_CODING_UINT, 
     (char*)"wlanChannelId", (char*)"" },
   { 0, IPFIX_FT_WLANSSID, 65535, IPFIX_CODING_STRING, 
     (char*)"wlanSSID", (char*)"" },
   { 0, IPFIX_FT_FLOWID, 8, IPFIX_CODING_UINT, 
     (char*)"flowId", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONDOMAINID, 4, IPFIX_CODING_UINT, 
     (char*)"observationDomainId", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTSECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowStartSeconds", (char*)"" },
   { 0, IPFIX_FT_FLOWENDSECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowEndSeconds", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTMILLISECONDS, 8, IPFIX_CODING_UINT, 
     (char*)"flowStartMilliseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWENDMILLISECONDS, 8, IPFIX_CODING_UINT, 
     (char*)"flowEndMilliseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTMICROSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"flowStartMicroseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWENDMICROSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"flowEndMicroseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTNANOSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"flowStartNanoseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWENDNANOSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"flowEndNanoseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWSTARTDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowStartDeltaMicroseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWENDDELTAMICROSECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowEndDeltaMicroseconds", (char*)"" },
   { 0, IPFIX_FT_SYSTEMINITTIMEMILLISECONDS, 8, IPFIX_CODING_UINT, 
     (char*)"systemInitTimeMilliseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWDURATIONMILLISECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowDurationMilliseconds", (char*)"" },
   { 0, IPFIX_FT_FLOWDURATIONMICROSECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"flowDurationMicroseconds", (char*)"" },
   { 0, IPFIX_FT_OBSERVEDFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"observedFlowTotalCount", (char*)"" },
   { 0, IPFIX_FT_IGNOREDPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"ignoredPacketTotalCount", (char*)"" },
   { 0, IPFIX_FT_IGNOREDOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"ignoredOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_NOTSENTFLOWTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"notSentFlowTotalCount", (char*)"" },
   { 0, IPFIX_FT_NOTSENTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"notSentPacketTotalCount", (char*)"" },
   { 0, IPFIX_FT_NOTSENTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"notSentOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_DESTINATIONIPV6PREFIX, 16, IPFIX_CODING_IPADDR, 
     (char*)"destinationIPv6Prefix", (char*)"" },
   { 0, IPFIX_FT_SOURCEIPV6PREFIX, 16, IPFIX_CODING_IPADDR, 
     (char*)"sourceIPv6Prefix", (char*)"" },
   { 0, IPFIX_FT_POSTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_POSTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postPacketTotalCount", (char*)"" },
   { 0, IPFIX_FT_FLOWKEYINDICATOR, 8, IPFIX_CODING_UINT, 
     (char*)"flowKeyIndicator", (char*)"" },
   { 0, IPFIX_FT_POSTMCASTPACKETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postMCastPacketTotalCount", (char*)"" },
   { 0, IPFIX_FT_POSTMCASTOCTETTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"postMCastOctetTotalCount", (char*)"" },
   { 0, IPFIX_FT_ICMPTYPEIPV4, 1, IPFIX_CODING_UINT, 
     (char*)"icmpTypeIPv4", (char*)"" },
   { 0, IPFIX_FT_ICMPCODEIPV4, 1, IPFIX_CODING_UINT, 
     (char*)"icmpCodeIPv4", (char*)"" },
   { 0, IPFIX_FT_ICMPTYPEIPV6, 1, IPFIX_CODING_UINT, 
     (char*)"icmpTypeIPv6", (char*)"" },
   { 0, IPFIX_FT_ICMPCODEIPV6, 1, IPFIX_CODING_UINT, 
     (char*)"icmpCodeIPv6", (char*)"" },
   { 0, IPFIX_FT_UDPSOURCEPORT, 2, IPFIX_CODING_UINT, 
     (char*)"udpSourcePort", (char*)"" },
   { 0, IPFIX_FT_UDPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
     (char*)"udpDestinationPort", (char*)"" },
   { 0, IPFIX_FT_TCPSOURCEPORT, 2, IPFIX_CODING_UINT, 
     (char*)"tcpSourcePort", (char*)"" },
   { 0, IPFIX_FT_TCPDESTINATIONPORT, 2, IPFIX_CODING_UINT, 
     (char*)"tcpDestinationPort", (char*)"" },
   { 0, IPFIX_FT_TCPSEQUENCENUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"tcpSequenceNumber", (char*)"" },
   { 0, IPFIX_FT_TCPACKNOWLEDGEMENTNUMBER, 4, IPFIX_CODING_UINT, 
     (char*)"tcpAcknowledgementNumber", (char*)"" },
   { 0, IPFIX_FT_TCPWINDOWSIZE, 2, IPFIX_CODING_UINT, 
     (char*)"tcpWindowSize", (char*)"" },
   { 0, IPFIX_FT_TCPURGENTPOINTER, 2, IPFIX_CODING_UINT, 
     (char*)"tcpUrgentPointer", (char*)"" },
   { 0, IPFIX_FT_TCPHEADERLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"tcpHeaderLength", (char*)"" },
   { 0, IPFIX_FT_IPHEADERLENGTH, 1, IPFIX_CODING_UINT, 
     (char*)"ipHeaderLength", (char*)"" },
   { 0, IPFIX_FT_TOTALLENGTHIPV4, 2, IPFIX_CODING_UINT, 
     (char*)"totalLengthIPv4", (char*)"" },
   { 0, IPFIX_FT_PAYLOADLENGTHIPV6, 2, IPFIX_CODING_UINT, 
     (char*)"payloadLengthIPv6", (char*)"" },
   { 0, IPFIX_FT_IPTTL, 1, IPFIX_CODING_UINT, 
     (char*)"ipTTL", (char*)"" },
   { 0, IPFIX_FT_NEXTHEADERIPV6, 1, IPFIX_CODING_UINT, 
     (char*)"nextHeaderIPv6", (char*)"" },
   { 0, IPFIX_FT_MPLSPAYLOADLENGTH, 4, IPFIX_CODING_UINT, 
     (char*)"mplsPayloadLength", (char*)"" },
   { 0, IPFIX_FT_IPDIFFSERVCODEPOINT, 1, IPFIX_CODING_UINT, 
     (char*)"ipDiffServCodePoint", (char*)"" },
   { 0, IPFIX_FT_IPPRECEDENCE, 1, IPFIX_CODING_UINT, 
     (char*)"ipPrecedence", (char*)"" },
   { 0, IPFIX_FT_FRAGMENTFLAGS, 1, IPFIX_CODING_UINT, 
     (char*)"fragmentFlags", (char*)"" },
   { 0, IPFIX_FT_OCTETDELTASUMOFSQUARES, 8, IPFIX_CODING_UINT, 
     (char*)"octetDeltaSumOfSquares", (char*)"" },
   { 0, IPFIX_FT_OCTETTOTALSUMOFSQUARES, 8, IPFIX_CODING_UINT, 
     (char*)"octetTotalSumOfSquares", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELTTL, 1, IPFIX_CODING_UINT, 
     (char*)"mplsTopLabelTTL", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKLENGTH, 4, IPFIX_CODING_UINT, 
     (char*)"mplsLabelStackLength", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKDEPTH, 4, IPFIX_CODING_UINT, 
     (char*)"mplsLabelStackDepth", (char*)"" },
   { 0, IPFIX_FT_MPLSTOPLABELEXP, 1, IPFIX_CODING_UINT, 
     (char*)"mplsTopLabelExp", (char*)"" },
   { 0, IPFIX_FT_IPPAYLOADLENGTH, 4, IPFIX_CODING_UINT, 
     (char*)"ipPayloadLength", (char*)"" },
   { 0, IPFIX_FT_UDPMESSAGELENGTH, 2, IPFIX_CODING_UINT, 
     (char*)"udpMessageLength", (char*)"" },
   { 0, IPFIX_FT_ISMULTICAST, 1, IPFIX_CODING_UINT, 
     (char*)"isMulticast", (char*)"" },
   { 0, IPFIX_FT_IPV4IHL, 1, IPFIX_CODING_UINT, 
     (char*)"ipv4IHL", (char*)"" },
   { 0, IPFIX_FT_IPV4OPTIONS, 4, IPFIX_CODING_UINT, 
     (char*)"ipv4Options", (char*)"" },
   { 0, IPFIX_FT_TCPOPTIONS, 8, IPFIX_CODING_UINT, 
     (char*)"tcpOptions", (char*)"" },
   { 0, IPFIX_FT_PADDINGOCTETS, 65535, IPFIX_CODING_BYTES, 
     (char*)"paddingOctets", (char*)"" },
   { 0, IPFIX_FT_COLLECTORIPV4ADDRESS, 4, IPFIX_CODING_IPADDR, 
     (char*)"collectorIPv4Address", (char*)"" },
   { 0, IPFIX_FT_COLLECTORIPV6ADDRESS, 16, IPFIX_CODING_IPADDR, 
     (char*)"collectorIPv6Address", (char*)"" },
   { 0, IPFIX_FT_COLLECTORINTERFACE, 4, IPFIX_CODING_UINT, 
     (char*)"collectorInterface", (char*)"" },
   { 0, IPFIX_FT_COLLECTORPROTOCOLVERSION, 1, IPFIX_CODING_UINT, 
     (char*)"collectorProtocolVersion", (char*)"" },
   { 0, IPFIX_FT_COLLECTORTRANSPORTPROTOCOL, 1, IPFIX_CODING_UINT, 
     (char*)"collectorTransportProtocol", (char*)"" },
   { 0, IPFIX_FT_COLLECTORTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     (char*)"collectorTransportPort", (char*)"" },
   { 0, IPFIX_FT_EXPORTERTRANSPORTPORT, 2, IPFIX_CODING_UINT, 
     (char*)"exporterTransportPort", (char*)"" },
   { 0, IPFIX_FT_TCPSYNTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpSynTotalCount", (char*)"" },
   { 0, IPFIX_FT_TCPFINTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpFinTotalCount", (char*)"" },
   { 0, IPFIX_FT_TCPRSTTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpRstTotalCount", (char*)"" },
   { 0, IPFIX_FT_TCPPSHTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpPshTotalCount", (char*)"" },
   { 0, IPFIX_FT_TCPACKTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpAckTotalCount", (char*)"" },
   { 0, IPFIX_FT_TCPURGTOTALCOUNT, 8, IPFIX_CODING_UINT, 
     (char*)"tcpUrgTotalCount", (char*)"" },
   { 0, IPFIX_FT_IPTOTALLENGTH, 8, IPFIX_CODING_UINT, 
     (char*)"ipTotalLength", (char*)"" },
   { 0, IPFIX_FT_POSTMPLSTOPLABELEXP, 1, IPFIX_CODING_UINT, 
     (char*)"postMplsTopLabelExp", (char*)"" },
   { 0, IPFIX_FT_TCPWINDOWSCALE, 2, IPFIX_CODING_UINT, 
     (char*)"tcpWindowScale", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONPOINTID_PSAMP, 8, IPFIX_CODING_UINT, 
     (char*)"observationPointId_PSAMP", (char*)"" },
   { 0, IPFIX_FT_SELECTIONSEQUENCEID, 8, IPFIX_CODING_UINT, 
     (char*)"selectionSequenceId", (char*)"" },
   { 0, IPFIX_FT_SELECTORID, 2, IPFIX_CODING_UINT, 
     (char*)"selectorId", (char*)"" },
   { 0, IPFIX_FT_INFORMATIONELEMENTID, 2, IPFIX_CODING_UINT, 
     (char*)"informationElementId", (char*)"" },
   { 0, IPFIX_FT_SELECTORALGORITHM, 2, IPFIX_CODING_UINT, 
     (char*)"selectorAlgorithm", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGPACKETINTERVAL, 4, IPFIX_CODING_UINT, 
     (char*)"samplingPacketInterval", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGPACKETSPACE, 4, IPFIX_CODING_UINT, 
     (char*)"samplingPacketSpace", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGTIMEINTERVAL, 8, IPFIX_CODING_NTP, 
     (char*)"samplingTimeInterval", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGTIMESPACE, 8, IPFIX_CODING_NTP, 
     (char*)"samplingTimeSpace", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGSIZE, 4, IPFIX_CODING_UINT, 
     (char*)"samplingSize", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGPOPULATION, 4, IPFIX_CODING_UINT, 
     (char*)"samplingPopulation", (char*)"" },
   { 0, IPFIX_FT_SAMPLINGPROBABILITY, 8, IPFIX_CODING_FLOAT, 
     (char*)"samplingProbability", (char*)"" },
   { 0, IPFIX_FT_DATALINKFRAMESIZE, 4, IPFIX_CODING_UINT, 
     (char*)"dataLinkFrameSize", (char*)"" },
   { 0, IPFIX_FT_IPHEADERPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"ipHeaderPacketSection", (char*)"" },
   { 0, IPFIX_FT_IPPAYLOADPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"ipPayloadPacketSection", (char*)"" },
   { 0, IPFIX_FT_DATALINKFRAMESECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"dataLinkFrameSection", (char*)"" },
   { 0, IPFIX_FT_MPLSLABELSTACKSECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsLabelStackSection", (char*)"" },
   { 0, IPFIX_FT_MPLSPAYLOADPACKETSECTION, 65535, IPFIX_CODING_BYTES, 
     (char*)"mplsPayloadPacketSection", (char*)"" },
   { 0, IPFIX_FT_PACKETSOBSERVED, 8, IPFIX_CODING_UINT, 
     (char*)"packetsObserved", (char*)"" },
   { 0, IPFIX_FT_PACKETSSELECTED, 8, IPFIX_CODING_UINT, 
     (char*)"packetsSelected", (char*)"" },
   { 0, IPFIX_FT_FIXEDERROR, 8, IPFIX_CODING_FLOAT, 
     (char*)"fixedError", (char*)"" },
   { 0, IPFIX_FT_RELATIVEERROR, 8, IPFIX_CODING_FLOAT, 
     (char*)"relativeError", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONTIMESECONDS, 4, IPFIX_CODING_UINT, 
     (char*)"observationTimeSeconds", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONTIMEMILLISECONDS, 8, IPFIX_CODING_UINT, 
     (char*)"observationTimeMilliseconds", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONTIMEMICROSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"observationTimeMicroseconds", (char*)"" },
   { 0, IPFIX_FT_OBSERVATIONTIMENANOSECONDS, 8, IPFIX_CODING_NTP, 
     (char*)"observationTimeNanoseconds", (char*)"" },
   { 0, IPFIX_FT_DIGESTHASHVALUE, 8, IPFIX_CODING_UINT, 
     (char*)"digestHashValue", (char*)"" },
   { 0, IPFIX_FT_HASHIPPAYLOADOFFSET, 8, IPFIX_CODING_UINT, 
     (char*)"hashIPPayloadOffset", (char*)"" },
   { 0, IPFIX_FT_HASHIPPAYLOADSIZE, 8, IPFIX_CODING_UINT, 
     (char*)"hashIPPayloadSize", (char*)"" },
   { 0, IPFIX_FT_HASHOUTPUTRANGEMIN, 8, IPFIX_CODING_UINT, 
     (char*)"hashOutputRangeMin", (char*)"" },
   { 0, IPFIX_FT_HASHOUTPUTRANGEMAX, 8, IPFIX_CODING_UINT, 
     (char*)"hashOutputRangeMax", (char*)"" },
   { 0, IPFIX_FT_HASHSELECTEDRANGEMIN, 8, IPFIX_CODING_UINT, 
     (char*)"hashSelectedRangeMin", (char*)"" },
   { 0, IPFIX_FT_HASHSELECTEDRANGEMAX, 8, IPFIX_CODING_UINT, 
     (char*)"hashSelectedRangeMax", (char*)"" },
   { 0, IPFIX_FT_HASHDIGESTOUTPUT, 1, IPFIX_CODING_BYTES, 
     (char*)"hashDigestOutput", (char*)"" },
   { 0, IPFIX_FT_HASHINITIALISERVALUE, 8, IPFIX_CODING_UINT, 
     (char*)"hashInitialiserValue", (char*)"" },
   { 0, 0, -1, 0, NULL, NULL, }
};
