#
# Makefile.w32 - kannel notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = kannel
SOURCES = $(wildcard *.cpp)
DRV_LIBS = $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
