#
# Makefile.w32 - leef (LEEF log exporter module) for Windows/MinGW
# Part of NetXMS project
#

MODULE = leef
SOURCES = $(wildcard *.cpp)
MOD_LIBS = -lnxdb

include $(TOPDIR)/src/server/module-common.mk
