SUBDIRS = db2 dbquery devemu ecs filemgr gps informix java jmx logwatch \
          lorawan mqtt mysql netsvc odbcquery oracle ping portCheck sms \
		  ubntlw ups winnt winperf wmi

include ..\..\..\Makefile.inc.w32
