#
# Makefile.w32 - ping subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = ping
SOURCES = ping.cpp scan_win32.cpp
SA_LIBS = -liphlpapi

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
