TARGET = libethernetip.dll
TYPE = dll
SOURCES = attr.cpp epath.cpp helpers.cpp main.cpp message.cpp session.cpp

CPPFLAGS = /DLIBETHERNETIP_EXPORTS
LIBS = libnetxms.lib ws2_32.lib
	  
include ..\..\..\Makefile.inc.w32
