#
# Makefile.w32 - mymobile notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = mymobile
SOURCES = $(wildcard *.cpp)
DRV_LIBS = -lnxjansson $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
