#!c:/apps/perl/bin/pelr -w

# $Id: mc.pl,v 1.4 2004-05-14 10:53:17 victor Exp $

###############################################################################
#
# VC++ message compiler alternative.
# read .mc files and generate corresponding source & include
#
###############################################################################

use strict;

# file names
my $inFile = shift || die "Usage : mc.pl <input_file>";
my $outHeader = $inFile;
$outHeader =~ s/\.[a-z]+$//;
my $outSource = $outHeader . ".c";
$outHeader .= ".h";

my $type = "DWORD";
my $messageId = 0;
my $comment;
my $symbolicName = "";
my %structData;

open(IN, "<$inFile") || die "input file: $!";
open(OUTH, ">$outHeader") || die "out header: $!";
open(OUTS, ">$outSource") || die "out source: $!";

while(<IN>) {
	chomp;
	my $in = $_;
	my $text = "";

	if ($in eq "") {
		next;
	}

	if ($in =~ /^[;#]+.*$/) {
		print OUTH substr($in, 1) . "\n";
		next; # comment -> skip
	}

	if ($in =~ /^MessageIdTypedef=([A-Z]+)$/i) {
		# typedef
		$type = $1;

		next;
	}

	if ($in =~ /^MessageId=([0-9]*)$/i) {
		if ($1 eq "") {
			$messageId++;
		} else {
			$messageId = $1 + 0;
		}

		next;
	}
	if ($in =~ /^SymbolicName=(.+)$/i) {
		$symbolicName = $1;

		next;
	}
	if ($in =~ /^Language=(.*)$/i) {
		# ignore language
		next;
	}

	# multiline text
	$text = $in;
	while(<IN>) {
		chomp;
		if ($_ ne ".") {
			$text .= "$_\n";
			# end
		} else {
			if ($symbolicName eq "") {
				last;
			}
			print OUTH "//\n// MessageId: $symbolicName\n//\n";
			print OUTH "// MessageText:\n//\n// ";
			$structData{$messageId} = $text;
			$text =~ s/\n/\n\/\//gm;
			print OUTH $text . "\n//\n";

			my $size = 8;
			if ($type =~ /^(WORD|short)$/i) {
				$size = 4;
			}
			printf OUTH ("#define %-30s (($type)0x%0" . $size . "x)\n\n", $symbolicName, $messageId);
			last;
		}
	}
}

print OUTS "/* autogenerated from $inFile */\n\n";
print OUTS "char *g_szMessages[] = {\n";

my @keys = sort {$b <=> $a} (keys %structData);

for (my $i = 0; $i < $keys[0]; $i++) {
	if (defined $structData{$i}) {
		$structData{$i} =~ s/\"/\\\"/g;
		print OUTS "\t\"" . $structData{$i} . "\"";
	} else {
		print OUTS "\t\"\"";
	}

	if ($i+1 == $keys[0]) {
		print OUTS "\n";
	} else {
		print OUTS ",\n";
	}
}

print OUTS "};\n";
print OUTS "\nunsigned long g_dwNumMessages = " . $keys[0] . ";\n";

close IN;
close OUTH;
close OUTS;
