#!/bin/sh

trap '
	rm -f tmp
' INT EXIT

if [ "x"$3 = "x" ]; then
	echo "Usage: $0 input.tar.gz scriptname output.sh"
	exit
fi

if [ ! -r $1 ]; then
	echo "Can't read $1"
	exit
fi

md5=`which md5 2>/dev/null`
if [ $? != 0 ]; then
	md5=`which md5sum 2>/dev/null`
	if [ $? != 0 ]; then
		md5=`which openssl 2>/dev/null`
		if [ $? != 0 ]; then
			echo "Can't calculate MD5, exiting"
			exit
		else
			md5="$md5 md5"
		fi
	fi
fi

case `uname -s` in
	Linux)
		#skip=`wc -l stub.sh|cut -d' ' -f1`
		skip=`cat stub.sh | wc -l | sed 's,^ *,,'`
		;;
	*BSD)
		skip=`echo \`wc -l stub.sh|cut -b1-8\``
		;;
	*)
		echo unknown system, duh
		exit;
		;;
esac
if [ "x$BASH" == "x" ]; then
	skip1=`let $skip+1`
else
	skip1=$skip
	let skip1++
fi

sed "s,__SKIP__,$skip,g" < stub.sh |
	sed "s,__SKIP1__,$skip1,g" |
	sed "s,__COMMAND__,$2,g" > tmp
hash1=`tail -n+5 tmp | $md5 | cut -b1-32 | tr A-Z a-z`
hash2=`cat $1 | $md5 | cut -b1-32 | tr A-Z a-z`
sed "s,__HASH1__,$hash1,g" < tmp | sed "s,__HASH2__,$hash2,g" > $3

cat $1 >> $3
