SUBDIRS = jansson libexpat libtre sqlite zlib libnetxms libnxlp libnxmb \
          libnxjava libnxsl libpng libstrophe nxscript db snmp appagent agent \
          client server smsdrv tools

include ..\Makefile.inc.w32
