SUBDIRS = jansson libexpat libtre sqlite zlib libnetxms libnxlp libnxmb \
          libnxjava libnxpython libnxsl libpng libstrophe nxscript db snmp \
          appagent agent client server tools

include ..\Makefile.inc.w32
