#
# Makefile.w32 - openmeteo subagent for Windows/MinGW
# Part of NetXMS project
#

SUBAGENT = openmeteo
SOURCES = main.cpp adapter.cpp location.cpp
SA_LIBS = -lnxjansson $(CURL_LIBS) $(SSL_LIBS)

include $(TOPDIR)/src/agent/subagents/subagent-common.mk
