#!/usr/bin/perl -w

use strict;
use DBI;
use CGI;

print "Content-type: text/html\nPragma: no-cache\n\n";

my $db = DBI->connect("DBI:mysql:database=netxms_web_db;host=10.0.0.4", "netxms_web", "n4tW0rkX", { RaiseError => 0 });

my $q = new CGI;

if (defined $q->param('del'))
{
	my $query = "DELETE FROM agentMatrix WHERE id=" . ($q->param('id') + 0);

	$db->do($query);
}
if (defined $q->param('edit'))
{
	my $query = "UPDATE agentMatrix SET ";
	if (defined $q->param('r1')) { $query .= "r1=1,"; } else { $query .= "r1=0,"; }
	if (defined $q->param('r2')) { $query .= "r2=1,"; } else { $query .= "r2=0,"; }
	if (defined $q->param('r3')) { $query .= "r3=1,"; } else { $query .= "r3=0,"; }
	if (defined $q->param('r4')) { $query .= "r4=1,"; } else { $query .= "r4=0,"; }
	if (defined $q->param('r5')) { $query .= "r5=1,"; } else { $query .= "r5=0,"; }
	if (defined $q->param('r6')) { $query .= "r6=1,"; } else { $query .= "r6=0,"; }
	if (defined $q->param('r7')) { $query .= "r7=1,"; } else { $query .= "r7=0,"; }
	if (defined $q->param('r8')) { $query .= "r8=1 "; } else { $query .= "r8=0 "; }
	
	$query .= "WHERE id=" . ($q->param('id') + 0);

	$db->do($query);
}
if (defined $q->param('add'))
{
	if ($q->param('name') ne '')
	{
		my $query = "INSERT INTO agentMatrix (param, r1, r2, r3, r4, r5, r6, r7, r8, type) VALUES (";
		$query .= "'" . $q->param('name') . "',";
		if (defined $q->param('r1')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r2')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r3')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r4')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r5')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r6')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r7')) { $query .= "1,"; } else { $query .= "0,"; }
		if (defined $q->param('r8')) { $query .= "1,"; } else { $query .= "0,"; }
		$query .= "'" . $q->param('type') . "')";

		$db->do($query);
	}
}


#####################
# html header
print <<"__END";
<html>
<head>
<title></title>
	<style>
		body, table, tr, td
		{
			font-family: Courier New;
			font-size: 10.0pt;
			border-collapse: collapse;
		}
		
		table
		{
			empty-cells: show
		}
		
		td
		{
			border: 1pt solid;
			padding: 0in 5.4pt;
		}

		.header
		{
			font-weight: bold;
		}
		
		.ready
		{
			text-align: center;
			background: #00ff00;
		}

		.notReady
		{
			text-align: center;
			background: #ff0000;
		}
	</style>
</head>
<body>
<h2>Parameters support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td class="header">Parameter</td>
		<td class="header">Windows</td>
		<td class="header">NetWare</td>
		<td class="header">Linux</td>
		<td class="header">FreeBSD</td>
		<td class="header">HPUX</td>
		<td class="header">AIX</td>
		<td class="header">Solaris</td>
		<td class="header">IPSO</td>
		<td class="header">[action]</td>
	</tr>
__END
#####################


my $sth = $db->prepare("SELECT id, param, r1, r2, r3, r4, r5, r6, r7, r8 FROM agentMatrix WHERE type = 'P' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<form action=\"/cgi-bin/matrixEdit\" method=\"POST\">";
	print "<input type=\"hidden\" name=\"id\" value=\"" . $rec->{id} . "\">";
	print "<tr><td class=\"param\">$rec->{param}</td>";
	$rec->{r1} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r1\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r1\"></td>";
	$rec->{r2} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r2\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r2\"></td>";
	$rec->{r3} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r3\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r3\"></td>";
	$rec->{r4} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r4\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r4\"></td>";
	$rec->{r5} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r5\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r5\"></td>";
	$rec->{r6} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r6\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r6\"></td>";
	$rec->{r7} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r7\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r7\"></td>";
	$rec->{r8} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r8\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r8\"></td>";
	print "<td style=\"text-align: center\"><input type=\"submit\" name=\"edit\" value=\"update\" style=\"width: 50%\"><input type=\"submit\" name=\"del\" value=\"delete\" style=\"width: 50%\"></td></tr></form>";
}
$sth->finish();

#####################
# table end
print <<"__END";
	<form action="/cgi-bin/matrixEdit" method="POST">
		<input type="hidden" name="type" value="P">
		<tr>
			<td style="text-align: center"><input type="text" name="name" style="width: 100%"></td>
			<td style="text-align: center"><input type="checkbox" name="r1"></td>
			<td style="text-align: center"><input type="checkbox" name="r2"></td>
			<td style="text-align: center"><input type="checkbox" name="r3"></td>
			<td style="text-align: center"><input type="checkbox" name="r4"></td>
			<td style="text-align: center"><input type="checkbox" name="r5"></td>
			<td style="text-align: center"><input type="checkbox" name="r6"></td>
			<td style="text-align: center"><input type="checkbox" name="r7"></td>
			<td style="text-align: center"><input type="checkbox" name="r8"></td>
			<td style="text-align: center"><input type="submit" name="add" value="add" style="width: 100%"></td>
		</tr>
	</form>
</table>
__END

#####################
# table start
print <<"__END";
<br /><h2>Enums support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0">
	<tr>
		<td class="header">Parameter</td>
		<td class="header">Windows</td>
		<td class="header">NetWare</td>
		<td class="header">Linux</td>
		<td class="header">FreeBSD</td>
		<td class="header">HPUX</td>
		<td class="header">AIX</td>
		<td class="header">Solaris</td>
		<td class="header">IPSO</td>
		<td class="header">[action]</td>
	</tr>
__END
#####################

$sth = $db->prepare("SELECT id, param, r1, r2, r3, r4, r5, r6, r7, r8 FROM agentMatrix WHERE type = 'E' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<form action=\"/cgi-bin/matrixEdit\" method=\"POST\">";
	print "<input type=\"hidden\" name=\"id\" value=\"" . $rec->{id} . "\">";
	print "<tr><td class=\"param\">$rec->{param}</td>";
	$rec->{r1} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r1\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r1\"></td>";
	$rec->{r2} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r2\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r2\"></td>";
	$rec->{r3} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r3\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r3\"></td>";
	$rec->{r4} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r4\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r4\"></td>";
	$rec->{r5} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r5\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r5\"></td>";
	$rec->{r6} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r6\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r6\"></td>";
	$rec->{r7} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r7\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r7\"></td>";
	$rec->{r8} == 1 ? print "<td class=\"ready\"><input type=\"checkbox\" name=\"r8\" checked></td>" : print "<td class=\"notReady\"><input type=\"checkbox\" name=\"r8\"></td>";
	print "<td style=\"text-align: center\"><input type=\"submit\" name=\"edit\" value=\"update\" style=\"width: 50%\"><input type=\"submit\" name=\"del\" value=\"delete\" style=\"width: 50%\"></td></tr></form>";
}
$sth->finish();


#####################
# table end
print <<"__END";
	<form action="/cgi-bin/matrixEdit" method="POST">
		<input type="hidden" name="type" value="E">
		<tr>
			<td style="text-align: center"><input type="text" name="name" style="width: 100%"></td>
			<td style="text-align: center"><input type="checkbox" name="r1"></td>
			<td style="text-align: center"><input type="checkbox" name="r2"></td>
			<td style="text-align: center"><input type="checkbox" name="r3"></td>
			<td style="text-align: center"><input type="checkbox" name="r4"></td>
			<td style="text-align: center"><input type="checkbox" name="r5"></td>
			<td style="text-align: center"><input type="checkbox" name="r6"></td>
			<td style="text-align: center"><input type="checkbox" name="r7"></td>
			<td style="text-align: center"><input type="checkbox" name="r8"></td>
			<td style="text-align: center"><input type="submit" name="add" value="add" style="width: 100%"></td>
		</tr>
	</form>
</table>
__END

#####################
# html footer
print <<"__END";
</body>
</html>
__END
#####################

#$db->do("INSERT INTO agentMatrix (param, r1, r2, r3, r4, r5, r6, r7, r8, type) VALUES ('$1', $2, $3, $4, $5, $6, $7, $8, $9, 'E')");

$db->disconnect();
