#!/usr/bin/perl -w

use strict;
use DBI;

print "Content-type: text/html\n\n";

my $db = DBI->connect("DBI:mysql:database=netxms_web_db;host=10.0.0.30", "netxms_web", "n4tW0rkX", { RaiseError => 0 });

#####################
# html header
if (defined $ENV{QUERY_STRING} && $ENV{QUERY_STRING} eq "")
{
	print <<"__END";
<html>
<head>
<title></title>
	<style>
		body, table, tr, td
		{
			font-family: verdana, helvetica, arial, sans-serif;
			font-size: 10.0pt;
			border-collapse: collapse;
			background: #ffffff;
		}

		html > body
		{
			font-size: 10.0pt;
		}

		.matrixParam
		{
			border: #000000 1pt solid;
			padding: 0in 5.4pt;
		}
		
		.matrixHeader
		{
			font-weight: bold;
		}
		
		.matrixReady
		{
			text-align: center;
			background-image: url('/supported.png');
			background-position: center; 
			background-repeat: no-repeat;
			border: #000000 1pt solid;
			padding: 0in 5.4pt;
		}

		.matrixNotReady
		{
			text-align: center;
			background-image: url('/unsupported.png');
			background-position: center; 
			background-repeat: no-repeat;
			border: #000000 1pt solid;
			padding: 0in 5.4pt;
		}
	</style>
</head>
<body>
__END
}

print <<"__END";
<h2>Parameters support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="300pix" class="matrixHeader">Parameter</td>
		<td class="matrixHeader" align="center" width="8%">Windows</td>
		<td class="matrixHeader" align="center" width="8%">NetWare</td>
		<td class="matrixHeader" align="center" width="8%">Linux</td>
		<td class="matrixHeader" align="center" width="8%">FreeBSD</td>
		<td class="matrixHeader" align="center" width="8%">HPUX</td>
		<td class="matrixHeader" align="center" width="8%">AIX</td>
		<td class="matrixHeader" align="center" width="8%">Solaris</td>
		<td class="matrixHeader" align="center" width="8%">IPSO</td>
	</tr>
__END
#####################


my $sth = $db->prepare("SELECT param, r1, r2, r3, r4, r5, r6, r7, r8 FROM agentMatrix WHERE type = 'P' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<tr><td class=\"matrixParam\">$rec->{param}</td>";
	$rec->{r1} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r2} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r3} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r4} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r5} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r6} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r7} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	$rec->{r8} == 1 ?
		print "<td class=\"matrixReady\"><span style=\"display: none\">X</span></td>"
			:
		print "<td class=\"matrixNotReady\"></td>";
	print "</tr>";
}
$sth->finish();

#####################
# table end
print <<"__END";
</table>
__END

#####################
# table start
print <<"__END";
<br /><h2>Enums support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="300pix" class="matrixHeader">Parameter</td>
		<td class="matrixHeader" align="center" width="8%">Windows</td>
		<td class="matrixHeader" align="center" width="8%">NetWare</td>
		<td class="matrixHeader" align="center" width="8%">Linux</td>
		<td class="matrixHeader" align="center" width="8%">FreeBSD</td>
		<td class="matrixHeader" align="center" width="8%">HPUX</td>
		<td class="matrixHeader" align="center" width="8%">AIX</td>
		<td class="matrixHeader" align="center" width="8%">Solaris</td>
		<td class="matrixHeader" align="center" width="8%">IPSO</td>
	</tr>
__END
#####################

$sth = $db->prepare("SELECT param, r1, r2, r3, r4, r5, r6, r7, r8 FROM agentMatrix WHERE type = 'E' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<tr><td class=\"matrixParam\">$rec->{param}</td>";
	$rec->{r1} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r2} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r3} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r4} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r5} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r6} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r7} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	$rec->{r8} == 1 ? print "<td class=\"matrixReady\"></td>" : print "<td class=\"matrixNotReady\"></td>";
	print "</tr>";
}
$sth->finish();


#####################
# table end
print <<"__END";
</table>
__END

#####################
# html footer
if (defined $ENV{QUERY_STRING} && $ENV{QUERY_STRING} eq "")
{
	print <<"__END";
</body>
</html>
__END
}
#####################

#$db->do("INSERT INTO agentMatrix (param, r1, r2, r3, r4, r5, r6, r7, r8, type) VALUES ('$1', $2, $3, $4, $5, $6, $7, $8, $9, 'E')");

$db->disconnect();
