#!/usr/bin/perl -w

use strict;
use DBI;

print "Content-type: text/html\n\n";

my $db = DBI->connect("DBI:mysql:database=netxms_web_db;host=10.0.0.4", "netxms_web", "n4tW0rkX", { RaiseError => 0 });

#####################
# html header
print <<"__END";
<html>
<head>
<title></title>
	<style>
		body, table, tr, td
		{
			font-family: verdana, helvetica, arial, sans-serif;
			font-size: 10.0pt;
			border-collapse: collapse;
			background: #ffffff;
		}

		html > body
		{
			font-size: 10.0pt;
		}
		
		table
		{
			empty-cells: show
		}
		
		td
		{
			border: #000000 1pt solid;
			padding: 0in 5.4pt;
		}

		.header
		{
			font-weight: bold;
		}
		
		.ready
		{
			text-align: center;
			background-image: url('/supported.png');
			background-position: center; 
			background-repeat: no-repeat;
		}

		.notReady
		{
			text-align: center;
			background-image: url('/unsupported.png');
			background-position: center; 
			background-repeat: no-repeat;
		}
	</style>
</head>
<body>
<h2>Parameters support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="300pix" class="header">Parameter</td>
		<td class="header">Windows</td>
		<td class="header">NetWare</td>
		<td class="header">Linux</td>
		<td class="header">FreeBSD</td>
		<td class="header">HPUX</td>
		<td class="header">AIX</td>
		<td class="header">Solaris</td>
	</tr>
__END
#####################


my $sth = $db->prepare("SELECT param, r1, r2, r3, r4, r5, r6, r7 FROM agentMatrix WHERE type = 'P' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<tr><td class=\"param\">$rec->{param}</td>";
	$rec->{r1} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r2} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r3} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r4} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r5} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r6} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r7} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	print "</tr>";
}
$sth->finish();

#####################
# table end
print <<"__END";
</table>
__END

#####################
# table start
print <<"__END";
<br /><h2>Enums support matrix</h2>
<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		<td width="300pix" class="header">Parameter</td>
		<td class="header">Windows</td>
		<td class="header">NetWare</td>
		<td class="header">Linux</td>
		<td class="header">FreeBSD</td>
		<td class="header">HPUX</td>
		<td class="header">AIX</td>
		<td class="header">Solaris</td>
	</tr>
__END
#####################

$sth = $db->prepare("SELECT param, r1, r2, r3, r4, r5, r6, r7 FROM agentMatrix WHERE type = 'E' ORDER BY param");
$sth->execute();
while (my $rec = $sth->fetchrow_hashref())
{
	print "<tr><td class=\"param\">$rec->{param}</td>";
	$rec->{r1} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r2} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r3} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r4} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r5} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r6} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	$rec->{r7} == 1 ? print "<td class=\"ready\"></td>" : print "<td class=\"notReady\"></td>";
	print "</tr>";
}
$sth->finish();


#####################
# table end
print <<"__END";
</table>
__END

#####################
# html footer
print <<"__END";
</body>
</html>
__END
#####################

#$db->do("INSERT INTO agentMatrix (param, r1, r2, r3, r4, r5, r6, r7, type) VALUES ('$1', $2, $3, $4, $5, $6, $7, $8, 'E')");

$db->disconnect();
