#
# Makefile.w32 - text2reach notification channel driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = text2reach
SOURCES = $(wildcard *.cpp)
DRV_LIBS = $(CURL_LIBS)

include $(TOPDIR)/src/server/ncdrivers/ncdrv-common.mk
