#
# Makefile.w32 - nxupload (agent file upload tool) for Windows/MinGW
# Part of NetXMS project
#

TOOL = nxupload
SOURCES = nxupload.cpp
TOOL_CPPFLAGS = -I$(TOPDIR)/src/server/include
TOOL_LIBS = -lnxsrv -lnetxms
# Entry point is _tmain (-> wmain under UNICODE)
TOOL_LDFLAGS = -municode

include $(TOPDIR)/build/tool-common.mk
