#
# Makefile.w32 - huawei network device driver for Windows/MinGW
# Part of NetXMS project
#

DRIVER = huawei
SOURCES = huawei.cpp lansw.cpp optix.cpp

include $(TOPDIR)/src/server/drivers/ndd-common.mk
