TARGET = nxagentd.exe
TYPE = exe
SOURCES = \
	actions.cpp appagent.cpp comm.cpp config.cpp ctrl.cpp \
	datacoll.cpp dcsnmp.cpp dbupgrade.cpp epp.cpp event.cpp \
	exec.cpp extagent.cpp getparam.cpp hddinfo.cpp localdb.cpp master.cpp \
	nxagentd.cpp policy.cpp proxy.cpp push.cpp register.cpp sa.cpp \
	service.cpp session.cpp snmpproxy.cpp snmptrapproxy.cpp \
	subagent.cpp sysinfo.cpp syslog.cpp tcpproxy.cpp \
	tools.cpp tunnel.cpp upgrade.cpp watchdog.cpp websvc.cpp
RESOURCES = nxagentd.rc
GENERATED = messages.h MSG00001.bin

LIBS = libnxagent.lib appagent.lib libnxsnmp.lib libnxdb.lib libnetxms.lib \
       jansson.lib pcre16.lib libcurl.lib libcrypto.lib ws2_32.lib wtsapi32.lib
	  
include ..\..\..\Makefile.inc.w32

nxagentd.rc: MSG00001.bin
